### ISSUE TITLE
optimize hyperapp h() calls 

### ISSUE THREAD

**Issue by pcariel** [hyperapp/hyperapp#145]
Hi, Friend. It is possible to create a plugin in babel to optimize the call of h().
example.

```js
// h() function invocation
h('div');

//optimized 
{
    tag: tag,
    data: data || {},
    children: children
  }
```

**Comment by dodekeract** [comment]
As far as I understand it wouldn't be possible to update the view then.

**Comment by jbucaran** [comment]
Hi @pcariel! 

HyperApp's architecture in a nutshell:

1. The user interacts with your application.
2. This triggers [actions](https://github.com/hyperapp/hyperapp/wiki/api#actions) which update the model.
3. When the model is updated, hyperapp automatically renders the [view](https://github.com/hyperapp/hyperapp/wiki/api#view).
4. Wash, rinse, repeat.

If we compile `h` calls into a vdom tree structure, we lose the ability to update the view like @dodekeract says, because the vdom engine will always see the same tree.

I hope that makes sense.

Now going to close here since this item is not actionable, but feel free to add more comments. 👋
