### ISSUE TITLE
Support for xlink:href

### ISSUE THREAD

**Issue by ngryman** [hyperapp/hyperapp#209]
Hey guys,

SVG support is currently incomplete, `use` does not work because `xlink:href` is a namespaced attribute that needs the couple `setAttributeNS`/`removeAttributeNS`.

I'm not opening a PR directly for this, but it's a rather common use case and I think we should support it.

Some references:
 - preact issue on the subject: https://github.com/developit/preact-svg/issues/15
 - preact-way: https://github.com/developit/preact/blob/33fc697ac11762a1cb6e71e9847670d047af7ce5/src/dom/index.js#L81

**Comment by jbucaran** [comment]
I was looking for an example to test xref:link, and found this on MDN.
> xlink:href
> Deprecated since SVG 2
> This feature has been removed from the Web standards...

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

Am I looking at the wrong page?

@lukejacksonn @ngryman @leeoniya

**Comment by ngryman** [comment]
No, but then there is browser support: https://www.chromestatus.com/feature/5760616295825408.
In real life, everybody still uses `svg 1.1`.

**Comment by ngryman** [comment]
On a side note, every frontend frameworks that I know and claims to support `svg` does support namespaced attribute.

**Comment by jbucaran** [comment]
@ngryman Sure, I just wanted to make sure I was not looking at the wrong page because I've never used xlink.

**Comment by lukejacksonn** [comment]
> What is the cost? ~10B minified gziped? What is the gain? It just vastly increase svg support for modern apps that use svg sprites.

I'm really in agreement here.. my hyperapp projects are the only projects that don't employ `<use>` tags, not because I don't prefer them anymore but because it isn't supported.

How much cleaner is:

```
const DeleteButton = () =>
  <button>
    <svg><use xlink:href="#icon-delete" /></svg>
  </button>
```

than the alternative:

```
const DeleteButton = () =>
  <button>
    <svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
      <path d="M0 0h24v24H0V0z" fill="none"/>
      <path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zm2.46-7.12l1.41-1.41L12 12.59l2.12-2.12 1.41 1.41L13.41 14l2.12 2.12-1.41 1.41L12 15.41l-2.12 2.12-1.41-1.41L10.59 14l-2.13-2.12zM15.5 4l-1-1h-5l-1 1H5v2h14V4z"/>
      <path d="M0 0h24v24H0z" fill="none"/>
    </svg>
  </button>
```

**Comment by leeoniya** [comment]
i'm 👍 on this from a practical standpoint. my current concern with adding it to domvm is the perf overhead of testing each attr name for namespace presence in a hot function. since it cannot be cheaply prefix-tested, running a regex of indexOf on every attr would greatly impact perf. there are some options tho.

- in domvm svg elems use their own factory, so perhaps plain vnodes can be saved from the overhead.
- a non-standard extra prefix would be cheap to test more generally: `:xlink:href` but is surprising
- rather than supporting any namespaced, just explicitly test for `xlink:href`, which is cheap.

for what it's worth, i plan to add support for this in domvm, but have to figure out which mix of the above ideas would result in least perf degredation. i think custom prefixing is DOA due to non-uniformity :(

**Comment by leeoniya** [comment]
i'll add that my above concerns only relate to runtime checks, which is all domvm has since there's no JSX compilation step. i dont think my reservations apply to frameworks where a preprocessor can easily make this a non-issue.

**Comment by ngryman** [comment]
@leeoniya @lukejacksonn Thanks for the feedback, let's continue on this thread where we are discussing an alternative solution for things like this: #211.
