### ISSUE TITLE
How to build an electron app using HyperApp?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#264]
You can build Electron apps using React, Vue, etc.

It would be awesome if we could do the same using HyperApp.

HyperTron? 😏

**Comment by Swizz** [comment]
You can build an Electron with litteraly everything is just a browser which capable to load only your content (JS, CSS, HTML).

I donc think, this need to be in the Hyperapp scope. Everyone who know well Electron, know it could be possible.
Samething with Cordova, Node-webkit, Crosswalk, etc.. 

*I am experimenting with Nativescript too.*

I love Hyperapp because its FIRST and KISS. I am running away from React, Vue, Ember because of thing everywhere.

**Comment by lukejacksonn** [comment]
I am going to do this next week, will push a template repo up when it is done and tested!

**Comment by lukejacksonn** [comment]
https://github.com/lukejacksonn/hyperapp-electron 😉

**Comment by jbucaran** [comment]
@lukejacksonn Looks super cool! Let's close here and add that nugget to the awesome list. 👊😄:+1:
