### ISSUE TITLE
[question] how to use third party libraries that modify the DOM

### ISSUE THREAD

**Issue by jcubic** [hyperapp/hyperapp#320]
I want to use tinyMCE editor in hyperapp is there a way to execute code after DOM render, other then mutation observer?

**Comment by jbucaran** [comment]
@jcubic Great question. One of the reasons I started this project was because I needed to put together a little app that used CodeMirror and found it extremely complex with other libraries.

The solution is similar to how you'd approach using react. You need to use lifecycle events. This is also briefly [mentioned on the documentation](https://github.com/hyperapp/hyperapp/blob/master/docs/lifecycle-events.md#codemirror-example).

- [CodeMirror example](https://hyperapp-codemirror.glitch.me/).

Good luck! 👋

**Comment by jcubic** [comment]
I've got error: `cm.options.theme.replace is not a function`, maybe codemirror changed the API.

**Comment by jbucaran** [comment]
@jcubic Thanks! It was a bug and I just fixed it. Should work now.
