### ISSUE TITLE
Add some notes about keys

### ISSUE THREAD

**Issue by MatejMazur** [hyperapp/hyperapp#322]
Hi, it would be great if we mention that array items ids are bad as keys (almost in all situations). 

It was difficult for me to find solution when I was learning with virtual DOM and simple reordering of list items was immediately broken because of that. Help others newbies with that. ☺️ 

Here is related article: https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318

**Comment by zaceno** [comment]
It seems react will warn you that something is missing keys sometimes - even when keys may not be be necessary, and that is why people tend to use array indices as keys (because they're there) as an easy way to silence the error messages. 

Since we don't warn you about missing keys, the problem is not the same in hyperapp. That said, I'm sure there are many who are unsure about how keys are supposed to be used and when (and why using art indices for keys is missing the point) I'll try to write something more clarifying.

**Comment by jbucaran** [comment]
@MatejMazur Added notes about keys. 

@zaceno If you can review them that'd be 💯.

**Comment by jorgebucaran** [comment]
## Summary

Keys help identify nodes every time we update the DOM. By setting the key property on a virtual node, you declare that the node should correspond to a particular DOM element. This allows us to re-order the element into its new position, if the position changed, rather than risk destroying it.

Keys must be unique among sibling nodes. Don't use an array index as a key, if the index also specifies the order of siblings. If the position and number of items in a list are fixed, it will make no difference, but if the list is dynamic, the key will change every time the tree is rebuilt.

###### Top-Level Nodes

In V1 and V2 keys are not registered on the top-level node of your view. If you are toggling the top-level view, and you must use keys, wrap them in an unchanging node. This may change in a future version of the VDOM.
