### ISSUE TITLE
How do you communicate between multiple components?

### ISSUE THREAD

**Issue by codingphasedotcom** [hyperapp/hyperapp#331]
First of all I apologize if this ain't the right platform to ask this question. I'm usually not a big fan of single page apps style of components so I like controlling my routes through the server and have multiple components in a page. Now I'm going over the documentation and the examples but can't figure out how to have multiple components share the same state or if thats even possible. I'm coming from a react state of mind where I would have multiple components share the same store. 

This is what I got so far. Again I'm a complete noob to ELM or HyperApp but I'm super excited to drink the koolaid. 
https://codepen.io/codingphase/pen/QMaBbM?editors=1111

**Comment by jbucaran** [comment]
Hi @codingphasedotcom 

Interoperability is explained to some extent here: https://github.com/hyperapp/hyperapp/blob/master/docs/events.md#interoperability

But using that technique only makes sense if you want to communicate with your app from the outside, from another existing app, etc. If you are making a new app from scratch, you would ideally have only one app() call.

> How to have multiple components share the same state or if thats even possible.

The container passes props down to a component and that component may father other components as pass props down to their children as well.

Whatever props you pass down come from the same global `state`, so by definition, all components  share the same state.

Does that help?

**Comment by codingphasedotcom** [comment]
hey @jbucaran,

Thanks for sending me in the right direction I don't know how I missed this.

**Comment by codingphasedotcom** [comment]
`If you are making an app from scratch, you should ideally have only one app() call.`

I bring back this example because 90% of the time I wont be able to have a parent component and then 2 children components. So in this example of the counter I'm trying to have two separate components but when I click up on 1 i want the other to have the same result. 
https://codepen.io/codingphase/pen/QMaBbM?editors=1111

I ask this because right now I have a filter section and a content section that are in complete different sections of the html. I want to be able to have access to the state of the filter component on the content component.

[alt text](http://i.imgur.com/J7bR9rR.png "Logo Title Text 1")

**Comment by jbucaran** [comment]
@codingphasedotcom Hmm, I think you are confused about components, which is okay, since you already you are coming from react.

[Components](https://github.com/hyperapp/hyperapp/blob/master/docs/components.md).

In hyperapp components are stateless, pure functions. There is no component local state or state isolation per-component. 

See also [State](https://github.com/hyperapp/hyperapp/blob/master/docs/state.md#state).

> The notion of representing the application state as a single source of truth is known as single state tree. The tree is manipulated using actions.

**Comment by zaceno** [comment]
@codingphasedotcom,

Like @jbucaran said, you *generally* want to strive for a single app(), because that way all your components will share a common state. Within that state, concerns may still be neatly separated (using some kind of lib to help like rambda in the example above or (shameless plug alert!) https://github.com/hyperapp-partial)

*That said*, if you must have multiple `app()` calls, as in your codepen example, it is fully possible for them to communicate and synchronize. Every call to `app({...})` returns a function; `emit` which you can use to send messages to that app. The messages are captured in the app's `events` property.

I forked your codepen and made some minor adjustments to make the counters sync. Have a look at: 
https://codepen.io/zaceno/pen/vJpPBY

(note: seems hyperapp's CDN broke right when I was in the middle of the final touches, so there may be a typo I haven't caught by the time it's working agin)

**Comment by jamen** [comment]
I will just reiterate what has already been said:

 1. There is no "private state", so all your components share the same state.
 2. There is no "private actions", so all your components can mutate the state the same ways.

With this provided, _communicating between components_ should be really simple, because they all have access to the same state and actions.

Take an example of two components.  One that displays some state, and another that mutates it.

```js
// Component that presents `state.feed`
function Feed (props) {
  return props.items.map(item =>
    <div class='feed-item'>{item}</div>
  )
}

function Input (props) {
  return <input onclick={props.onsubmit} placeholder='Add to feed' />
}
```

Then when initialized, we pass them the proper info from the view:

```js
// The display:
<Feed items={state.items} />

// The input:
<Input onsubmit={actions.createItem} />
```

This is a watered down example, hopefully it makes sense.  :smile:

**Comment by zaceno** [comment]
Kudos @jamen for clarifying what a "component" means in hyperapp-land. @codingphasedotcom can be forgiven for being confused, as an `app({...})` looks a lot like a component in Vue. (And, I presume, React also)

**Comment by jamen** [comment]
Thanks.  I think it is also important to clarify how they don't just _have access_ to state and actions, as @jbucaran described it:

> In Hyperapp components are stateless, pure functions. There is no local state. Hyperapp components are not like your react components.

They are "stateless", and you pass pieces of the app's state, and also actions so it knows how to mutate it.

As some "workaround" to this, I've seen people just do:

```js
<Component state={state} actions={actions} />
```

This is nice!  But also, it's a nice modeling what data/actions your component needs sometimes.

**Comment by selfup** [comment]
You can also you use the `emit` pattern! Kind of like EventHub in Vue if you are familiar with that pattern.

I understand that everyone explains that a single `app()` is preferred but it is not that easy to do in a legacy code base.

Here is an example of a plain JS function talking to an instance of hyperapp (which two apps can do vice versa no problem): https://codepen.io/selfup/pen/jLMRjO

JS:

```javascript
/** @jsx h */
const { h, app } = hyperapp;

const HYPERHUB = app({
  state: { num: 0 },
  actions: {
    hello: (state, actions, { num }) => {
      console.log(num);
      return { num };
    },
  },
  events: {
    dispatch: (state, actions, { action, data }) => {
      return actions[action]
        ? actions[action](data)
        : null;
    },
  },
  view: (state, actions) => 
    <div>
      <h1>{state.num}</h1>
    </div>,
  root: document.querySelector('#app'),
});

const dispatch = (action, data) => HYPERHUB(
  'dispatch',
  { action, data },
);

dispatch('hello', { num: 42 });

// not hyperapp stuff calling hyperapp through hyperhub
document.addEventListener('click', ({ target }) => {
  switch(target.id) {
    case '9000':
      dispatch('hello', { num: 9000 });
      break;
    case '42':
      dispatch('hello', { num: 42 });
      break;
    default:
      null;
      break;
  }
});
```

HTML:

```html
<button id="9000">HyperHub 9000 from regular JS</button>
<button id="42">Back to 42</button>

<div id="app"></div>

<script src="https://unpkg.com/hyperapp"></script>
```

**Comment by codingphasedotcom** [comment]
WOW I'm loving this community... really thank you guys. For explaining this in such a detail. I definitely will be going through this framework this weekend like crazy. I just cant tackle things here like I would with react or vue.  @zaceno appreciate that you forked it because i can see what you did and understand how I should implement this in our website at 39dollarglasses.com
