### ISSUE TITLE
Source Code Comments Anyone?

### ISSUE THREAD

**Issue by okwolf** [hyperapp/hyperapp#341]
First I would like to thank the team for a great developer experience getting started with Hyperapp as a user. The docs are just detailed enough to be useful 👍 

As a potential contributor I also appreciate how much more approachable the source is compared to projects like React, but there's still enough complexity that I believe measured use of code comments would be of great benefit to us and future you. I'm referring mostly to parts related to events and the VDOM in `src/app.js`. I know we want to keep this as lean as possible, but comments should be stripped out in minification, right?

**Comment by jbucaran** [comment]
@okwolf This is still a WIP, but https://git.io/how-hyperapp-works.

I usually don't like to comment code, because then I find myself wasting time thinking about things like writing style, grammar, text justification and other aesthetic considerations.

**Comment by jbucaran** [comment]
When I finally get the time to finish the guide, I'll provide the full annotated source in that link.

**Comment by okwolf** [comment]
@JorgeBucaran is there going to be an updated version of [this](https://gist.github.com/JorgeBucaran/8dc33b7947f3193eb2ea3d5700e27036) after we release 1.0.0?

**Comment by JorgeBucaran** [comment]
@okwolf Totally.

**Comment by okwolf** [comment]
@JorgeBucaran _bump_

Has the time arrived yet?

**Comment by JorgeBucaran** [comment]
Haha okay, let me see what I can do 😉😄😏

**Comment by JorgeBucaran** [comment]
I am working on those implementation notes right now! 💪 

Here is an appetizing gif for the meantime. 


![2018-01-02 12 54 52](https://user-images.githubusercontent.com/56996/34473961-43057426-efbc-11e7-8134-5c0fca586608.gif)

**Comment by selfup** [comment]
So just going to add that we should focus on `patch` and maybe functions with optional args.

Since everything else has REALLY good function names. Patch is the hard part, but I don't think `set` /`get`/ `getKey`/`setElementProp`/`etc..` need comments. I think the functions that have optional arguments should have a small comment explaining why (size optimization/optional render).

Patch on the other hand should have comments though. It is a complex function that is more than 8 lines long, and is the meat and bones of how VDOM works (which is what most people want to learn by reading the source anyway).
