### ISSUE TITLE
Can i use it with just node.js?

### ISSUE THREAD

**Issue by quko8** [hyperapp/hyperapp#351]
When i try use it as core of my app 
`
const { app } = require('hyperapp')
console.log(app({}))
`
i got error: `ReferenceError: document is not defined`.

Can i use it with nodejs?

**Comment by zaceno** [comment]
@quko8 it can certainly work under node.js, but since node.s doesn't have a built in DOM-engine, you'll need to import/require one. 

I use `undom` in my tests, for instance. To make your example work, try `npm install undom` and then:

```js
require('undom/register')
const {app} = require('hyperapp')
console.log(app({}))
```

... I'm not sure that will work, though, as I believe might complain if you haven't defined a state and view, at least (or maybe that's been changed recently)

**Comment by jbucaran** [comment]
Neither a state or a view is strictly necessary, so it should work (or fail for a different reason! 😄).

**Comment by quko8** [comment]
i think using undom isn't a good idea for production usage.
i think it's OK for test only :-(

**Comment by zaceno** [comment]
Sure that's true, I misunderstood then. But what is your production-use-case? SSR? You could have a look at https://github.com/hyperapp/server

**Comment by zaceno** [comment]
@quko8 Hang on... what's the problem with using undom in production? Is it unstable or something?  Anyway, theres jsdom if you prefer that. Regardless: hyperapp needs to execute in an environment where there is a DOM api, because it's made for producing dynamic DOM's

**Comment by jbucaran** [comment]
Thanks @quko8 & @zaceno. I think the question has been answered.

In short: No, you can't use the hyperapp module on the server without jsdom, etc. This might be possible in the future or be done via hyperapp/server though.
