### ISSUE TITLE
to render the app with custom root, that element MUST have at least a child

### ISSUE THREAD

**Issue by devhero** [hyperapp/hyperapp#356]
I've struggled while setting the root because the page didn't render. I used the official root's doc example:

    <body>
      <div id="app"></div>
    </body>

But js broke always with an undefined 'element'.
Inquiring the code I've found that in app.js the main element is choose in this way:

    var appRoot = props.root || document.body
    var element = appRoot.children[0]

so it's necessary to have at least one child (any tag), that will be replaced by the application, eg. like this:

    <body>
      <div id="app">
        <i></i>
      </div>
    </body>

Maybe it has to be mentioned in the doc.

**Comment by selfup** [comment]
That is interesting 🤔 

https://codepen.io/selfup/pen/jLMRjO

This works just fine without a child in the custom root.

What version of hyperapp are you using?

**Comment by devhero** [comment]
I have tried with 0.12.1 and 0.12.0, both suffer of this.

**Comment by selfup** [comment]
@devhero could I see an example of your `app({ ... })`? or at least the main view you call?

Thanks!

**Comment by devhero** [comment]
In fact, if you inspect the html code generated by codepen, the <div id="app"> does not contain the app, instead it's appended to the body. So IMO that test is not reliable.

**Comment by selfup** [comment]
It seems that it's going into the correct element?

<img width="992" alt="screen shot 2017-09-08 at 10 10 33 am" src="https://user-images.githubusercontent.com/9837366/30215456-07cd4616-947e-11e7-9c51-d2552c39148e.png">

**Comment by selfup** [comment]
@devhero https://unpkg.com/hyperapp@0.12.1/dist/hyperapp.js is what version the codepen is pulling in. Hmm

@jbucaran @lukejacksonn Can you explain this behavior? Thanks!

**Comment by selfup** [comment]
@devhero I followed the simple example from our docs and it seems to work just fine:

https://codepen.io/selfup/pen/KvjJBb?editors=1010

**Comment by jbucaran** [comment]
Hi @devhero!

> ...so it's necessary to have at least one child (any tag), that will be replaced by the application...

I am really curious, because that's definitely **not the case**, never will and has never been! 👋😄   

---

```html
<!doctype html>
<html>

<body>
  <body>
    <div id="app"></div>
  </body>

  <script src="bundle.js"></script>
</body>

</html>
```

```js
import { h, app } from "hyperapp"

app({
  view: () => <h1>Hi.</h1>,
  root: document.getElementById("app")
})
```

<img width="556" alt="screen shot 2017-09-09 at 0 11 35" src="https://user-images.githubusercontent.com/56996/30218280-a018e694-94f3-11e7-85a9-2781c9e16e0b.png">


---

> @devhero Inquiring the code I've found that in app.js the main element is choose in this way...

```js
var element = appRoot.children[0]
```

Ah, you observed well, but your conclusion is incorrect. The patch function will create a new element when `element` is undefined, which is the case when the `root` (or document.body by default) is empty.


---

> @devhero In fact, if you inspect the html code generated by codepen, the
>
> does not contain the app, instead it's appended to the body. So IMO that test is not reliable.

I inspected the HTML code generated by CodePen and **it looks good to me**.

<img width="416" alt="screen shot 2017-09-09 at 0 07 55" src="https://user-images.githubusercontent.com/56996/30218147-3cfecfa6-94f3-11e7-9870-0c2d6541a458.png">

<img width="468" alt="screen shot 2017-09-09 at 0 07 40" src="https://user-images.githubusercontent.com/56996/30218156-47d21604-94f3-11e7-9525-016f2641fd0d.png">
<img width="767" alt="screen shot 2017-09-09 at 0 08 39" src="https://user-images.githubusercontent.com/56996/30218145-3a09d9a8-94f3-11e7-8dca-ee42f1356c46.png">

---

@selfup's last example [here](https://github.com/hyperapp/hyperapp/issues/356#issuecomment-328117923) also works spotlessly! 💯 

I am going to close here as invalid, but feel free to reopen if you come back with a working example.

**Comment by devhero** [comment]
Ok, I've tested your examples and they works. (You are saying 'really!?').
I really appreciate this library, is very simple and smart!

I reanalyzed my code and I found that the problem happens on load event, while fetching initial data.
I come from react and I have some difficults without the help of methods like 'componentDidMount'.

I have prepared a simple example where I explain the issue:
https://jsfiddle.net/vsgdxmd5/4/

Thanks for the help!

**Comment by jbucaran** [comment]
@devhero 

The problem is here:

```js
  events: {
    load: (state, actions) => actions.loadItems()
  },
```

It should be:
```js
  events: {
    load: (state, actions) => {
      actions.loadItems()
    }
  }
```

**Comment by jbucaran** [comment]
It's not really your fault, this is a pitfall because while you are never encouraged to return anything from `events.load`, the docs don't tell you to be careful either.

We use `events.load` for hydration of pre-rendered (or SSR) HTML. See [here](https://github.com/hyperapp/hyperapp/blob/master/docs/hydration.md).

**Comment by devhero** [comment]
Ok, thanks A LOT!

**Comment by selfup** [comment]
Oh glad we found the root cause here (no pun intented 😂)

Yea this was a tricky one 😛
