### ISSUE TITLE
No Protections Against XSS Attacks Using innerHTML

### ISSUE THREAD

**Issue by okwolf** [hyperapp/hyperapp#360]
If someone were building an app with Hyperapp and wanted to allow for formatting of user-supplied data with HTML instead of Markdown or other such syntax, using the `innerHTML` attribute adds a XSS vulnerability that we should probably at least warn about if not prevent entirely.

[Example pen](https://codepen.io/okwolf/pen/XavOKy?editors=0010).

In React this would be prevented with the message:

```
Warning: Directly setting property `innerHTML` is not permitted. For more information, lookup documentation on `dangerouslySetInnerHTML`.
```

As the warning implies, the [dangerouslySetInnerHTML](https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml) attribute is React's way of allowing the user to still do this while acknowledging how dangerous it is.

**Comment by zaceno** [comment]
Hmm... My personal feeling: It's not hyperapp's responsibility to protect users from shooting themselves in the foot when they chose to work directly with the DOM. Perhaps a note somewhere in the lifecycle event docs (which is where we expose the DOM directly)

React's approach sounds a lot like it started as a secure-coding-policy internally at Facebook, which they decided to just build into "their" framework as a convenience for themselves.

(Maybe I'm being a little cynical. But really -- innerHTML is not any more "dangerous" then anything else. As always, you just have to know what you're doing when dealing with user supplied data)

**Comment by okwolf** [comment]
@zaceno I'm all for not trying to idiot-proof the API, but it is a very real concern that beginner developers might not be aware of. At a minimum I think we should document the dangers of this gotcha if we don't add any special handling. Especially for users converting from React who rely on the safety features it provides.

**Comment by selfup** [comment]
Yea in the docs I would follow the same warning as Vue does:

https://vuejs.org/v2/api/#v-html

Simple, clear warning 👍

**Comment by jbucaran** [comment]
So, what solutions have we come up with so far?

- Disable innerHTML and give you dangerouslySetInnerHTML to do the same.
- Document using innerHTML is dangerous.

...

**Comment by okwolf** [comment]
@jbucaran we could also choose to disable `innerHTML` and not provide any work-around, but that would probably be too disruptive.

My vote right now is for documenting along the lines of: **Here Be Dragons** 🐲

**Comment by SkaterDad** [comment]
My vote is documentation.  No need to add the extra complexity in my
opinion.

It's a good candidate for "Dev mode" console warnings in the future also.

**Comment by selfup** [comment]
Shall we close?

https://github.com/hyperapp/hyperapp/pull/361/files#diff-3f6ea3864d4d859d7715a9d46c40d4e3R56

**Comment by jbucaran** [comment]
@okwolf Maybe we can add a **Caveats** or **Warnings** section instead and add a few more sentences about XSS and how to sanitize?

**Comment by christiankaindl** [comment]
Maybe also point out to use `textContent` instead?

MDN says following:

> *Differences from innerHTML*:
Element.innerHTML returns the HTML as its name indicates. Quite often, in order to retrieve or write text within an element, people use innerHTML. However, textContent often has better performance because the text is not parsed as HTML. **Moreover, using textContent can prevent XSS attacks.**

https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent

**Comment by selfup** [comment]
Hmm, I think this situation is a bit different 🤔 But I do appreciate the reference to MDN 🎉 

If I have a backend API that returns HTML (markdown to html for example), I can't use textContent for that. 

Also in some apps, where the svgs are an API response (you cannot animate a `background-image` in an SVG _with CSS_). You must have the encoded (compiled) SVG to be able to use CSS animations. This is where `innerHTML` is useful as well 🚀 

**If** we add `textContent` in the docs as an example, we _must_ explain that this is only for replacing a string and that using `h`/`hyperx`/`jsx` solves this problem in the first place 👍 

I would rather avoid adding confusion and seeing people use `textContent` instead of utilizing the VDOM 👍. What do you think @christiankaindl?

I think as long as we explain that using `innerHTML` **without sanitized user content**/**trusted content** is a bad idea.

And if the user is just returning a string, then `<span>{state.string}</span>` will be all that is needed.

Thanks for bringing it up though! ❤️

**Comment by christiankaindl** [comment]
I think many people don't know about `textContent` and that in a lot of places they use `innerHTML` where they just want to insert text. I myself stumbled upon it not long ago and was surprised that I had never seen it before. But this is a very generic issue and it is probably a good idea to prioritize VDOM.

Maybe something like this:

---
**Warning**: use of the `innerHTML` [method](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#Security_considerations) can lead to [cross-site scripting (XSS)](https://en.wikipedia.org/wiki/Cross-site_scripting) vunerabilities if not properly sanitized. If you find yourself using it be careful and/or consider using HyperApp's built in `h` function (or `jsx` or `hyperx`) instead.

---

thanks @selfup for the nice reply!

**Comment by leeoniya** [comment]
FWIW, in domvm's docs i recommend using DOMParser [1] before resorting to innerHTML [2].

[1] https://developer.mozilla.org/en-US/docs/Web/API/DOMParser
[2] https://github.com/leeoniya/domvm#innerhtml

**Comment by selfup** [comment]
@christiankaindl Thanks for explaining and providing a nice example of what could be used in the docs 🎉 

I am glad my reply helped with why using `innerHTML` is sometimes necessary 😄 

Really dig the example you gave 👍

**Comment by pspeter3** [comment]
Does hyperapp sanitize text nodes and attributes?

**Comment by SkaterDad** [comment]
@pspeter3 https://github.com/hyperapp/hyperapp/blob/master/src/app.js#L149

It uses the Dom element setAttribute function.

**Comment by jbucaran** [comment]
https://github.com/hyperapp/hyperapp/commit/3ab5a1e483fc0520447b3280c52ec67c84f66ff1

😄
