### ISSUE TITLE
[RFC] Components & Mixin Guidelines

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#365]
Mixins and components are **not** the same thing! 

We use components to describe parts of our app, like a TabBar, a ToggleButton, SlideButton, etc., and mixins to extend the state, actions and events of our app. 

_To extend_ means that we will merge your mixins state/actions/events with your app state/actions/events to create a single state/actions/events. 

But often you need to pass actions to your component via props. 

[CodePen](https://codepen.io/jbucaran/pen/GMRjRB?editors=0010)

```js
function ToggleButton({ toggle, isOn }) {
  return ( < /* ... */ > )
}

app({
  actions: {
    toggle(state) {
      return { isOn: !state.isOn }
    }
  },
  view(state, actions) {
    return <ToggleButton toggle={actions.toggle} isOn={state.isOn} />
  }
})
```

This makes components, in a way, really "hollow" as we must teach it pretty much everything so it can thrive in the world. **This is good**, as it makes components extremely easy to test and debug. But what if the implementation of those actions is provided by a mixin? 

In that case I think the mixin and component should be tucked away into their own module.

A good example of this is our friendly Router's Link component.

```js
import { router, Link } from "@hyperapp/router"

app({
  view: [
    [
      "/",
      (state, actions) =>
        <Link to="/test" go={actions.router.go}>
          Test
        </Link>
    ],
    [
      "/test",
      (state, actions) =>
        <Link to="/" go={actions.router.go}>
          Back
        </Link>
    ]
  ],
  mixins: [router()]
})
```

Notice how we must teach Link `actions.router.go`, which is fed to our actions by the `router()` mixin. I mean, it's not so bad right? Just a little repetition is not so bad and this makes the Link component easy to test and debug and all that, right?

Sure! but the Link component would be just as easy to test and debug and all that if it shipped with `actions.router.go` already "pre-wired"... as long as you can overwrite the action and pass it a new one, just like it's done above.

There is [a PR here](https://github.com/hyperapp/router/pull/20) addressing just this. The idea is to be able to rewrite the example above as follows:

```js
import { h, app } from "hyperapp"
import { router } from "@hyperapp/router"

app({
  view: (state, actions, { Route }) => <Route />,
  mixins: [
    router([
      [
        "/", (state, actions, { Link }) =>
          <Link to="/test">
            Test
          </Link>
      ],
      [
        "/test", (state, actions, { Link }) =>
          <Link to="/">
            Back
          </Link>
      ]
    ])
  ]
})
```

Notice now we don't need to teach the Link `actions.router.go` anymore! 💯 

On the other hand, see that we now need to grab the pre-wired Link component somehow, since:

```js
import { Link } from "@hyperapp/router"
``` 

...would take us back to square one (wouldn't work unless we pass `actions.router.go` ourselves).

The benefit is less boilerplate, but it comes at a cost: we need to overload the `view` function with a third argument! 🤔 

**The good news** is that none of this requires changes in core! 🎉 

This is already possible using [`events.render`](https://github.com/hyperapp/hyperapp/blob/master/docs/events.md#render).

But  the real question to me is which way is more expensive? Overloading the view function or having to manually wire components every time we use them?

The only caveat about overloading the view function is you **need to make sure** not to break other authors also overloading the function. This is already solved, of course, using "namespaces", which fortunately we already support.

```js
actions: {
  myNamespace: {
  // My actions
  },
  yourNamespace: {
  // Your actions
  },
  ...
}
```

Now, while the Router and Link component are good examples to introduce this idea, we could easily shrug it off and get away without it just as we have done until now.

IMO more complex components will benefit from this pattern. Imagine a rich text editor in Hyperapp.

It could look as follows:

```js
import { h, app } from "hyperapp"
import { editor } from "./editor"

app({
  view(state, actions, { editor: Editor }) {
    return <Editor />
  },
  mixins: [editor({/*...*/})]
})
```

Compare how it might look like without overloading the view function:

```js
import { h, app } from "hyperapp"
import { Editor, editor } from "hyperapp-rt-editor"

app({
  view: (state, actions) => (
      <Editor state={state.editor} actions={actions.editor} />
  ),
  mixins: [editor({/* ... */})]
})
```

Not the worst, but I prefer the previous pattern. What about you? 

Whichever style you end up choosing for your own components+mixins is ultimately up to you. 

 :wave:

**Comment by zaceno** [comment]
👍 for `view(state, actions, {editor: Editor}) => <Editor />`

**Comment by lukejacksonn** [comment]
`<Editor />` > `<Editor state={state.editor} actions={actions.editor} />`

**Comment by andrewfluck** [comment]
I'm all for view(state, actions, { mixin: Component })

**Comment by zaceno** [comment]
All who have answered and/or reacted seem unanimous 😄 

Perhaps we can go ahead and merge https://github.com/hyperapp/router/pull/20 then?

**Comment by jbucaran** [comment]
@zaceno Yes, let's give it a few more days though! :)

/cc @andyrj @ngryman @jamen @SkaterDad

**Comment by SkaterDad** [comment]
Like the other comments so far, I'm highly in favor of this pattern.  It's a really elegant solution, which in my opinion fits the way hyperapp already deals with actions, state, etc.

**Comment by jamen** [comment]
I love the direction this has gone. Probably will start using that personally.  I was trying to go for something like that back in https://github.com/hyperapp/hyperapp/issues/235, but the idea had major drawbacks.  This is a great! :smile:

**Comment by andyrj** [comment]
I agree with @zaceno and @lujejacksonn.  The overloaded view with third param is cleaner.

**Comment by infinnie** [comment]
Maybe a good old jQuery event handler would solve the aforementioned problem:
```jsx
app({
    // ...
    view: function () {
        return <a href="/test" data-route-link="true">Go</a>;
    },
    root: $("#root").get(0),
    mixins: router(),
    events: {
        load: function (state, actions) {
            $("#root").on("click", "[data-route-link=true]", function () {
                actions.route.go($(this).prop("href"));
                return false;
            });
        }
    }
});
```

**Comment by jbucaran** [comment]
@inf This is off-topic, but just a heads-up, you can rewrite that `load` event as follows:

```js
...
    events: {
        load(state, actions) {
            $("#root").on("click", "[data-route-link=true]", function () {
                actions.route.go($(this).prop("href"));
                return false;
            });
        }
    }
```

**Comment by okwolf** [comment]
@jbucaran the inconvenient 800-pound gorilla in the room is that this is amounts to a single-level form of dependency injection that trades one problem for another. In a more realistic example you would probably have separate components for the views of each route instead of inlining the entire view. Then you would still need a way to pass the pre-wired™ `Link` component to each of your components for different routes. Unfortunately the current [calls to component functions](https://github.com/hyperapp/hyperapp/blob/3ab5a1e483fc0520447b3280c52ec67c84f66ff1/src/h.js#L31) only take `data` and `children` so today you would have to pass the `Link` component as data (or props as they are called in [React](https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components) and [Vue.js](https://vuejs.org/v2/guide/components.html#Props)).

React provides [context](https://facebook.github.io/react/docs/context.html#parent-child-coupling) as their solution to this exact problem (it's even used by [React Router](https://github.com/ReactTraining/react-router)) but I always found context to be hacky and it comes with severe discouragement against use from the creators. I wish I had a proposal for how we can resolve this part of the issue. Maybe after some more thought... 🤔

**Comment by SkaterDad** [comment]
@okwolf It certainly is dependency injection, but it's no different than how actions already work, in my opinion.  I agree it probably has downsides, though.

I don't use JSX, so my "higher level" view functions usually have the signature `function MyView(state, actions) { .... }`.   I definitely see your point about how this extra "views/widgets" parameter would be somewhat inconvenient in JSX.   However, I think it's becoming more popular in React to pass in view functions to a component, so... it's not _too_ weird?  [`downshift` is a recent example](https://github.com/paypal/downshift#this-solution).

Another potential downside is these injected components are harder to tree-shake/dead-code-eliminate?  Not sure how the bundler or uglify would know if you're only using 2 of the 10 components you've injected from a mixin.  For components I'm making myself, for my own apps, this is probably not a big deal, since I can just comment out what I'm not using.  But for someone using a library of components using this method, it could be a more complicated problem.

I'm totally comfortable using this pattern for the router mixin, since the components are all necessary when using the router.  I'm also totally cool with it for creating custom components I'll use throughout my app.  Would I bring in a whole "material design" component library this way?  Tougher decision.

Like every other discussion in programming, it's all about what trade-offs you prefer, I suppose 😄

**Comment by Mytrill** [comment]
I feel there is something I am missing here, but why not something like this?  
Link.js
```javascript

let defaultGo
export const setDefaultGo = (go) => {
  defaultGo = go
}

export function Link(props, children) {
  //...
  props.onclick = function(event) {
    //...
    event.preventDefault()
    
    if(props.go) {
      props.go(props.href)
    } else if(defaultGo) {
      defaultGo(props.href)
    }
  }

  return h("a", props, children)
}
```

router.js:
```javascript
import { setDefaultGo } from './Link'

export function router(options) {
  return function(emit) {
    return {
      events: {
        load: function(state, actions) {
          // at this time the actions are already wired
          setDefaultGo(actions.router.go)
        }
      }
    }
  }
}
```

This particular implementation is quite dirty (and NOT tested) but something of this type should work no?

**Comment by zaceno** [comment]
@Mytrill the notion of exporting pre wired components rather than "injecting" them as discussed here, has been explored to some extent in this PR: https://github.com/hyperapp/router/pull/20 but was not as popular. 

Your method has a technical problem though, which is: what if there are multiple apps on a page, and they all include your mixin? Which "go" should we use? Granted it's not likely a problem with your example, because when would anyone realistically use multiple routers in a single page :-P ... but still, for other mixins that are meant to be reusable, we can't rely on closures in module scope because that will be shared between apps that use the mixin.

**Comment by jacktuck** [comment]
>To extend means that we will merge your mixins state/actions/events with your app state/actions/events to create a single state/actions/events.

If i'm not misunderstanding and mixins are just for extending state, i'm more partial to higher-order components/functions.

```
import { Editor, editor } from "hyperapp-rt-editor"

const App = app({
  view: (state, actions) => (
      <Editor state={state.editor} actions={actions.editor} />
  ),
})

export default editor({})(App)
```

**Comment by JorgeBucaran** [comment]
@jacktuck You won! We are not moving forward with this. 🎉 

See: #219
