### ISSUE TITLE
Transclusion / Passing Mixings

### ISSUE THREAD

**Issue by joseph-montanez** [hyperapp/hyperapp#398]
I am a user of RiotJs and started messing with HyperApp. One problem I am running into is how transclusion/yielding works. It seems that mixins are going away in version 1.0 of HyperApp so all of this may be moot.

Below is an example of using the child view to pass `actions` into it and here is the snippet that's important:

```
    {Layout({page: 'hello.html'}, {reverse, foo})}
    <Layout page="hello.html">{{reverse, foo}}</Layout>
```

I realize this is probably beyond HyperApp, but when doing something like using HyperApp's Router, I end up with a lot of JSX expressions rather than HTML because of the need to pass in `actions` from the `app` definition. It seems that I can bypass the need of using expressions and fallback to HTML if I pass in the actions as the child elements/views, or I just keep it simple and use the element attributes `actions={{reverse, foo}}`. If I pass in actions as the child elements, then `actions` comes back as an array which provides an inconsistent experience from the `root` view.

https://codepen.io/anon/pen/eGeYoG?editors=1111

```
const { h, app } = hyperapp
/** @jsx h */

const Layout = (state, actions) => {
  console.log(state, actions);
  actions.foo('called from layout');
  return (
    <div>
      Page Title
    </div>
  );
  
};

app({
  state: {
    title: "Taco cat"
  },
  view: ({ title }, {reverse, foo}) =>
  <div>
    <h1 onclick={reverse}>{title}</h1>
    {Layout({page: 'hello.html'}, {reverse, foo})}
    <Layout page="hello.html">{{reverse, foo}}</Layout>
  </div>,
  actions: {
    foo (bar) { console.log(bar) },
    reverse(state) {
      return {
        title: state.title.split("").reverse().join("")
      }
    }
  }
});
```

Overall it would be nice to have the ability to create a view and pass along the mixin with the same setup as a root view. I saw some discussions on app composition so maybe I am going about this all wrong.

**Comment by Mytrill** [comment]
There is a HUGE difference between the lines `<Layout page="hello.html">{{reverse, foo}}</Layout>` and `Layout({page: 'hello.html'}, {reverse, foo})`.
The first gets transpiled to `h(Layout, {page: 'hello.html'}, {reverse, foo})` where `h()` expects `Layout` to be a `Component`, i.e. a function with the type signature `(props: object, children: VNode[]) => VNode`.
As you see the `children` parameter there is an array, and part of `h()`'s job is to make sure it is indeed an array (so that we don't have complicated code to write to handle children in our components).
In your snippet, Layout is not a component, since it does not have the correct type signature, therefore you should not use JSX/h

The second is just a function call.

If you want both calls to be equivalent (and Layout to be a component), you have to rewrite the code this way:
```
const Layout = (props, children) => {
  console.log(props.page, props.actions);
  actions.foo('called from layout');
  return (
    <div>
      Page Title
    </div>
  );
  
};

//...
<div>
    <h1 onclick={reverse}>{title}</h1>
    {Layout({ page: 'hello.html', actions: { reverse, foo } })}
    <Layout page="hello.html" actions={{reverse, foo}}></Layout>
  </div>
//...
```

Also see views: https://github.com/hyperapp/hyperapp/blob/master/docs/view.md
VS components: https://github.com/hyperapp/hyperapp/blob/master/docs/components.md

**Comment by JorgeBucaran** [comment]
Hi @joseph-montanez, I didn't have much time to address this issue as I was working on #385. Now with that out of the way, I can take a look. Where you able to fix whatever problem you were having or do you have any other question? 

👋
