### ISSUE TITLE
1kb file size?

### ISSUE THREAD

**Issue by xz64** [hyperapp/hyperapp#4]
Hi, just wondering how you arrived at the 1kb file size, when app.min.js.gz is 1.7kb in this repo. 

Also I think it would be good to state the size of `html.min.js` somewhere in the README if that's not factored into the file size.

**Comment by jbucaran** [comment]
> Hi, just wondering how you arrived at the 1kb file size, when app.min.js.gz is 1.7kb in this repo.

It's a stretch.

> Also I think it would be good to state the size of html.min.js somewhere in the README if that's not factored into the file size.

It's not factored in the file size, because `html` is a straightforward export of [hyperx](https://github.com/substack/hyperx).

Just like JSX is compiled into `createClass` calls using Babel, we could use https://github.com/shama/yo-yoify to compile 

```
html`<h1>Your HTML here</h1>`
```

into raw `h` calls. Or use Babel to compile JSX into raw `h` calls. I just haven't looked into it.

Related
* https://jasonformat.com/wtf-is-jsx/

**Comment by xz64** [comment]
Thanks

**Comment by jorgebucaran** [comment]
V2 will mark the end of an era as Hyperapp transitions from 1 kB into 2 kB. For that reason I've decided to modify the description of the project to:

> Hyperapp is a JavaScript micro-framework for building web applications.
