### ISSUE TITLE
CLI tool ala create-react-app to scaffold HyperApp apps

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#41]

**Comment by tunnckoCore** [comment]
I think it should be separate package, first. Second it can use the `hyperapp-one` boilerplate and also it would be good to promote it in the readme : )

**Comment by jbucaran** [comment]
We're thinking the same.

**Comment by tunnckoCore** [comment]
Name, arguments order / commands, prefs?

**Comment by tunnckoCore** [comment]
Maybe the name should `create-hyperapp`? Or simply `hyperapp-cli`. I'm for the last. :)

**Comment by jbucaran** [comment]
🤔 I like -cli because it's short, but I think the name depends on how the tool would work.

Let's discuss how and what the tool should be about, and later decide the name?

Should we do something like create-react-app?

**Comment by liadbiz** [comment]
@jbucaran   agree.  use  hyperapp-cli for runing example code locally, create-hyper-app for getting boilerplate created buy user.

**Comment by selfup** [comment]
since there are multiple options, it should be like:

`create-hyperapp jsx my-new-project`

`create-hyperapp html my-newproject`

JSX will be webpack

HTML will be browserify so that hyperxify can work (will use CJS by default)

**Comment by jbucaran** [comment]
@selfup LGTM.

It would make rollup the default though, since that's what HyperApp itself uses and I've found produces the smallest bundles. Rollup pioneered tree-shaking so they deserve it.

Ideally, it should be able to use other stuff too, as well as simpler, less specialized setups. 

A beginner user doesn't need a powerful configuration, but a clear bird's eye view of all the moving parts and a simpler configuration is that.

**Comment by lukejacksonn** [comment]
The below links might be useful for anyone looking at creating anything `create-hyperapp` like (they came from @jbucaran on the slack channel). I think it's a great idea, `create-react-app` is a useful tool. Offering something similar feels fitting. Also here for convenience [hyperapp-one](https://github.com/selfup/hyperapp-one).

- [hyperapp + jsx + rollup + buble minimal boilerplate](https://gist.github.com/jbucaran/f714dd6d64041591e5e53dbff8558439)
- [hyperapp + jsx + rollup minimal boilerplate](https://gist.github.com/jbucaran/0c0da8f1256a0a66090151cfda777c2c)
- [hyperapp + jsx + webpack minimal boilerplate](https://gist.github.com/jbucaran/6010a83891043a6e0c37a3cec684c08e)
- [hyperapp + hyperx + browserify minimal boilerplate](https://gist.github.com/jbucaran/48c1edb4fb0ea1aa5415b6686cc7fb45)
- [hyperapp + jsx + browserify minimal boilerplate](https://gist.github.com/jbucaran/21bbf0bbb0fe97345505664883100706)


Just thinking out loud here but, what about some options like the following, with some sensible defaults or flag similar to `npm init --yes` which says, just get on with it :boom::

```
-> create-hyperapp
--> Name: my-app
--> Markup: html|jsx
--> Bundler: rollup|webpack|browserify
--> Template: helloworld|counter|input|dragndrop|todo
```

I might look at it this weekend. @tunnckoCore mentions @generate I've never it before, how does it fair in comparison with yeoman? Definitely the way to go?

**Comment by jbucaran** [comment]
I am not familiar with generate, but I know yeoman. 

I'd go with a standalone, dependency free mini tool instead. Something minimal, just like HyperApp.

I have nothing against yeoman, but IIRC, yeoman forces the user to install `yo` globally. Does @generate do the same thing?

**Comment by jbucaran** [comment]
I kinda like the direction choo went with [choo-cli](https://github.com/trainyard/choo-cli), what do you think @lukejacksonn?

**Comment by lukejacksonn** [comment]
I see, so partial templates as well project scafolding.. I like!

**Comment by jbucaran** [comment]
Yeah, nice, but still, even simpler that choo-cli. If you look at the excellent Youtube walkthrough of the tool, you might experience flashing deja-vus, that is, if you have any experience working with Rails 😄

**Comment by lukejacksonn** [comment]
Yeh I checked [that video](https://www.youtube.com/watch?v=FgYd3T8lb_Q) out but have no rail experience so it was all quite new to me anyway 🚂🔥🔥🔥 Looked like a nice api.. it could have been a much less verbose process though yeh.

What does it need to do then `hyperapp-cli` what is the first command `new` perhaps? What does that do, presumably takes a project name and basically generates a project structure similar to that of `hyperapp-one`?

**Comment by jbucaran** [comment]
@lukejacksonn Yes, maybe. Depends on what features the generator has right? What do you think would be the best CLI? What should the generator be able to do?

Do we want something like `choo generate` to generate specific parts of the project, like just a directory with the model or views or effects. I personally find this overkill, but I could be wrong.

**Comment by lukejacksonn** [comment]
Ima sleep on this!

**Comment by tunnckoCore** [comment]
@jbucaran @lukejacksonn Generate is much more configurable, easy and flexible. Absolutely every thing is a very small plugin or generator, doing one thing. But yea, i'm for small cli tool too.

As about the example from the Gists, Rollup has a plugin for JSX, so it would fit well for users which don't use babel, just Rollup + `rollup-plugin-jsx`. But yea, I kinda don't like it because the plugin don't have tests and not respect JSX pragma comment - you should pass `{ factory: 'h' }` in options of the plugin.

As about the commands:

- `hyperapp new my-project` - should just generate a project structure without existing files like seen in hyperapp-one. Should not prompt, this would be delegated to the other commands.
- `hyperapp model counter` - generates a file in `./models` folder
- `hyperapp effect counter` - generates a file in `./effects` folder
- `hyperapp reducer counter` - generates a file in `./reducers` folder
- `hyperapp view counter` - generates a file in `./views` folder
- etc
- `hyperapp use rollup` - installs needed dependencies (hence, `npm-install` or `yarn-install` packages)  and generates needed rollup config file
- `hyperapp use babel` - same, but adds `.babelrc`
- `hyperapp use browserify` - same
- `hyperapp use babel-rollup` - or `rollup-babel` for the config that is rollup but using the babel plugin; it should generate babelrc and rollup.config.js

**Comment by jbucaran** [comment]
@lukejacksonn Does it make sense to have a hyper-cli/hyperapp-cli?

**Comment by zaceno** [comment]
@jbucaran, I know you asked @lukejacksonn, but I'm going to throw in my 2c here:  One of the things I like best about hyperapp is how you can just start coding. I think we should have a CLI but we need to think about how we make sure people don't miss out on the pleasant simplicity of going bare-bones.

I mean people are so used to *needing* the CLI from other frameworks, they may never even consider trying without it.

My fear is, that if everyone is approaching hyperapp through a CLI, the differentiating factors become less apparent.

**Comment by lukejacksonn** [comment]
This feels like a lonnng time ago now! I am in agreement really; people want a CLI because they don't want to have to type out a load of boilerplate / create big file structures.

HyperApp doesn't demand so much so why bother.. this is probably why one hasn't materialised.

Personally I've been working on a [template](https://github.com/lukejacksonn/hyperapp-pwa) that I just clone and then quickly go round renaming application specific keys things like names, descriptions, titles, icons, deployable domain etc. Nothing more has to change as I am satisfied with using rollup and JSX (or more recently just h). It works fine.

But every time I do this I think.. I wish there was an `hyperapp-init <project_name>` then just went and did a find/replace job on these variables and even create me a repo and push up an initial commit.

Not sure this is really hyperapp specific but it wouldn't be hard to create and would really help people jump straight into coding, like you say!

**Comment by rileytg** [comment]
rails templates are kinda like what you're describing. personalized starters that have basic find and replace type functionality

**Comment by jbucaran** [comment]
It would be fun if there was a service we could curl for the template in a tarball instead.

```sh
curl hyperapp.in/starter | tar -xzf
```

**Comment by andyrj** [comment]
I really like the way vue-cli handles their templates in GitHub repos, simple handle bar esque syntax and the prompts we're fairly easy to modify.  Personally I would be tempted to see if we could just fork and rebrand that client ;) just 2cents from the new guy

**Comment by rileytg** [comment]
^ yes those are very easy!

reminds me of kubernetes helm charts

**Comment by Pyrolistical** [comment]
good to see minimal boilerplate examples of hyperapp + jsx + webpack

I _hate_ fully integrated production ready bbq templates. Those are just useless to me to understand how stuff works.

**Comment by jbucaran** [comment]
@Pyrolistical https://github.com/hyperapp/hyperapp/issues/41#issuecomment-280823376

> Those are just useless to me to understand how stuff works.

Oh, I know that feeling! 😏

**Comment by tunnckoCore** [comment]
oh god, you finally unblocked me.

**Comment by lukejacksonn** [comment]
@tunnckoCore 👋 welcome back!

**Comment by jbucaran** [comment]
@tunnckoCore I never meant to block you forever, if you can have civilized discussions, I am ready to have them! 👋

**Comment by jbucaran** [comment]
This issue has been open for the longest time now! 🎉 

I'll cut to the case. I am not interested on a CLI tool to scaffold a new hyperapp project at this moment (but I could change my mind). I mostly agree with @lukejacksonn in that:

> HyperApp doesn't demand so much so why bother.. this is probably why one hasn't materialised.
