### ISSUE TITLE
Don't lock render before calling view function.

### ISSUE THREAD

**Issue by lukejacksonn** [hyperapp/hyperapp#422]
Recently I have been playing around with modules that map external state of things like `mouse`, `scroll` and `location` to hyperapp state. I have observed that it certain cases when `update` is called in rapid succession; that the data used in the last render is not the data in the state.

If I remove the skip render check (but leave rAF), the behaviour goes away:
```
function repaint() {
  if (props.view) { requestAnimationFrame(render) }
}
```

I started looking at [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) as I haven't used it since I experimented with WebGL years ago. From what I can gather:

- Requests that the browser call a specified function before the next repaint
- You should call this method whenever you're ready to update your view onscreen

It doesn't say anything about skipping renders 🤔 and it makes me wonder why we are doing this? I have always thought of `requestAnimationFrame` as like a smart debounce/throttle which you throw whatever you want at, and it makes sure not to over compute.

Looking at the current setup it seems that a state update `assign(state, data)` could be made, which calls `repaint()` when `skipRender` is true meaning that `render` is never called. This would explain the behaviours I have witnessed.

Interestingly removing all trace of `skipRender` seems to have no adverse effects at all on hyperapp even when challenged with rapid state updates. Do we need it for some reason I am not remembering?

**Comment by JorgeBucaran** [comment]
@lukejacksonn skipRender debounces the [`render()`](https://github.com/hyperapp/hyperapp/blob/d6ca900a95e4d9c7ce695e8c2602c50627a64b30/src/app.js#L21) function.

skipRender prevents enqueuing multiple calls to render, i.e., avoids calling requestAnimationFrame(render) multiple times.

If we don't use skipRender, we will request a render for every state change.

> I have observed that it certain cases when update is called in rapid succession; that the data used in the last render is not the data in the state.

How to repro this? Do you have a demo?

**Comment by JorgeBucaran** [comment]
@lukejacksonn I've updated the issue description based on our convo earlier today and my understanding of the issue.

Basically, we want the ability to call actions inside components (which will update the state and trigger re-renders).

**Comment by SkaterDad** [comment]
@lukejacksonn  @JorgeBucaran Are you talking about calling actions directly inside the `view` functions, and not in response to a user action (like clicks)?

From the last post, this is what I'm imagining:
```js

view: (state, actions) => {
  if (state.needSomething) {
    actions.fetchStuff()
  }
  return h('div', {}, 'Text')
}

```

**Comment by JorgeBucaran** [comment]
> @SkaterDad Are you talking about calling actions directly inside the view functions...

Yes. Basically any actions called inside the view function or functions called inside the view (e.g., Components) will invalidate the state, so when the view function returns the state will be out of sync with the computed vnode.

The idea is to compute the vnode and before patching the DOM, detect whether the state was invalidated (in other words, detect if a re-render has been scheduled already) and if so return early, otherwise proceed as usual.

**Comment by SkaterDad** [comment]
Can you elaborate more on the actual use case which triggered this discussion?

That seems counter to `hyperapp`'s reason-to-be in my opinion, which is applying functional concepts in a simple/compact way.  In other functional things, like elm and cycle.js, effects can really only happen in response to a user event.

If we start calling actions inside the view, essentially triggering side effects, you break the functional purity of the view.

It also introduces another set of complications, since the whole view function gets called every time state updates, and you would need a way to prevent those actions from being called unnecessarily.

At that point, you might as well be using stateful components.

**Comment by JorgeBucaran** [comment]
> @SkaterDad At that point, you might as well be using stateful components.

That's an overstatement. I am not planning on calling any functions inside the view now anywhere, but I don't want to limit users either. 

By the way, there's nothing preventing you from calling an action inside the view right now. The problem is that if you do it, the view will not reflect the latest state until the next re-render, which can only be caused by calling another action.

With this feature, you wouldn't have to worry about anything. A possible use case is implementing a Redirect component that changes the location.pathname and updates the state.

**Comment by SkaterDad** [comment]
> @JorgeBucaran That's an overstatement. I am not going to start calling actions inside the view, but I don't want to limit anyone who wants to do it.

You're right, I apologize for my tone here.  People should be able to do whatever they want, and get the expected result.  By adding framework support for this, you're endorsing the pattern.  My personal opinion is this would be a good candidate for a "dev mode" warning message.  I'll see myself out now :athletic_shoe:

**Comment by JorgeBucaran** [comment]
@SkaterDad I think I am making a big deal of this, when it's really a very small change in core. That probably led you to believe that this is going to shake our functional paradigm.

First, this is the implementation:

```js
function render() {
  var next
  lock = !lock
  if ((next = props.view(globalState, globalActions)) && !lock) {
    flush((root = patchElement(container, root, node, (node = next))))
  }
}
```

Second, this issue is directly related to your comment [here](https://github.com/hyperapp/router/pull/23#issuecomment-337901575) and its trigger was implementing route entry guarding, the very same thing you were asking.

/cc @lukejacksonn

**Comment by JorgeBucaran** [comment]
> @SkaterDad It also introduces another set of complications, since the whole view function gets called every time state updates, and you would need a way to prevent those actions from being called unnecessarily.

Definitely, and that's already taken care of. See the implementation above.

**Comment by SkaterDad** [comment]
> If you could join us on slack, you'd see, it was a 2 hour long discussion with Luke.

Unfortunately my work blocks Slack, so I miss out on that sort of thing.  I look forward to seeing what comes out of it, though. :+1:

**Comment by lukejacksonn** [comment]
@SkaterDad as @JorgeBucaran said.. this nearly directly stemmed from your queries about routing (namely route guards and fetching data). I was playing around with possible router implementations and discovered a shortcoming of a component based configuration when trying to implement a `Redirect` component which looked like this:

```
const Redirect = props => {
  props.when && props.go(props.to)
}

app({
  view: (state, actions) => main([
    Redirect({ when: !state.user, go: actions.router.go, to: '/login' }),
    Route({ path: '/', view: Home }),
    Route({ path: '/login', view: Login }),
  ])
})
```

This works but leaves the state and the view state _out of sync_ as described above. This is because we are trying to call an action whilst rendering, and when we are rendering any subsequent calls to render are blocked. The proposal here https://github.com/hyperapp/hyperapp/pull/424 doesn't stop the locking per se, but allows for us to _interrupt_ a render, saying to hyperapp.. woahh there, I know you wanted to go ahead and render all that content, but the state has changed since you started so bail out early and start again.

This is not so different from a user interaction.. imagine this (contrived) example:
```
const Redirect = props => a({ href: props.to, oncreate: e => props.when && e.click() })
```

Here the component is just doing the _click_ for the user. This is emulating user interaction which, in your book, is allowed:

> effects can really only happen in response to a user event.

But this is hacky right.. and it would be nice if we could just write it as a function.

Personally I don't find anything wrong or see shortcomings of calling functions in views, after all `h` is just a function.. it might even make things simpler!
```
div([
  !state.data.length && actions.fetchData(),
  state.fetching ? div('Fetching..') : ul(state.data.map(li))
])
```

**Comment by SkaterDad** [comment]
@lukejacksonn I agree that last snippet looks appealing.  The dynamic nature of component routes is also pretty neat.

I'm hesitant because of the way `hyperapp` re-runs the whole `view()` function on every state update.   In your sample, it wouldn't be an issue unless some other action (potentially unrelated) triggered a state update before your `actions.fetchData()` finished.  In that case, you'll end up calling `fetchData()` again.  

Easy enough fix in this case, but does this approach scale up to even more complicated apps?  Some ideas could be borrowed from [RemoteData for elm](http://package.elm-lang.org/packages/krisajenkins/remotedata/4.3.1/RemoteData#RemoteData)?

```js
div([
  !state.fetching && actions.fetchData(),
  state.fetching ? div('Fetching..') : ul(state.data.map(li))
])
```

I look forward to being able to play around with this approach.  For now, I built a HOA routing solution that works for me (routes pre-defined and passed in up front), so I might be able to upgrade my main project from 0.12.1 at long last 😄
