### ISSUE TITLE
0.16.0: Uncaught TypeError: Cannot read property 'preventDefault' of undefined

### ISSUE THREAD

**Issue by leifoolsen** [hyperapp/hyperapp#448]
Hello,

I Have the following code, which works fine in 0.15.1:

View snippet:
```js
export const view = (state, actions) =>
  <div>
    <a href="/" onclick={actions.page}>Home</a>
  </div>;
```

Action snippet
```js
export const actions = {
  page: (state, actions, event) => {
    event.preventDefault();
    return { page: '/foo' };
  },
```
After upgrading to 0.16.0, calling preventDefault results in the following error:

```
Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at Object.page (http://localhost:8084/app.js:9876:11)
    at HTMLAnchorElement.actions.(anonymous function) (http://localhost:8084/app.js:8294:33)
```

The function in HyperApp that causes the error
```js
  function initDeep(state, actions, from, path) {
    Object.keys(from || {}).map(function(key) {
      if (typeof from[key] === "function") {
        actions[key] = function(data) {

          // The line that causes the error
          var result = from[key]((state = get(path, appState)), actions)
         ....   
  }

```

Are there any breaking changes regarding how events are handled?

**Comment by JorgeBucaran** [comment]
Hi @leifoolsen! I still haven't had time to update the release notes, explaining how to upgrade from <0.16.0, but in your case the solution is:

```js
export const actions = {
  page: state => event => {
    event.preventDefault();
    return { page: '/foo' };
  },
```

**Comment by leifoolsen** [comment]
Hi @JorgeBucaran. Thanks for reply. 
Using a chained function worked 👍

**Comment by Swizz** [comment]
Hi @leifoolsen, just a brief poll. As you are a user. 

What is your thoughts about this API change ?

**Comment by JorgeBucaran** [comment]
![2](https://user-images.githubusercontent.com/56996/32418929-848dc09e-c2b5-11e7-9a95-7d52ce2f0bc9.jpg)
![1](https://user-images.githubusercontent.com/56996/32418930-84b5b0a4-c2b5-11e7-9d43-ff44fa43a9e5.jpg)

**Comment by leifoolsen** [comment]
Hi @Swizz. Currying is ok, but probably need some documentation.

**Comment by leifoolsen** [comment]
Also the init function from #406 seems to be missing in 0.16.0
```js
app({
  init(state, actions) {
    // Subscribe to global events, start timers, fetch resources & more!
  },
  state,
  actions,
  view,
  modules: { whopper, mouse }
})
```
How do I write the init function  in 0.16.0?

**Comment by JorgeBucaran** [comment]
@leifoolsen Still haven't had time to work on the release notes, but I will today. Here is the same code snippet updated for 0.16.0.

```js
const actions = app({
  state,
  actions,
  view,
  modules: { whopper, mouse }
})

// Subscribe to global events, start timers, fetch resources & more!
```

**Comment by JorgeBucaran** [comment]
@leifoolsen Still haven't had time to work on the release notes, but I will today. Here is the same code snippet updated for 0.16.0.

```js
const actions = app({
  state,
  actions,
  view,
  modules: { whopper, mouse }
})

// Subscribe to global events, start timers, fetch resources & more!
```

**Comment by leifoolsen** [comment]
@JorgeBucaran Thans for reply.
I'll try that. 
As I understand it (after some debugging), only actions are exposed from app. If I need access to state object (for e.g. copying to local storage) I must use an action?

**Comment by JorgeBucaran** [comment]
@leifoolsen You only had access to the initial state inside `init`, so if you need access to the initial state outside the app, just put the state in a variable and use it.

```
const state  = { loggedUser: "me" }

const { commit } = app({ state, view, actions })

if (state.loggedUser !== "") {
   commit(state.loggedUser)
}
```

This is unlikely, though. You would probably be better off just calling an action, which can access the state and do something with it.

Does this answer your question?

**Comment by lukejacksonn** [comment]
Another solution to this is to make a component out of it. If you wanted to fetch a state from local storage when the app loads, and then store all subsequent state, you could create a component that accepts root level state/actions. If it is the first render then `setup === false` so we do some stuff, in this case we read from `localStorage` and replace our apps state with the value, using `actions.commit`. If the component is already setup then the state must be new, so put it in storage.

```js
let setup = false
const Tardis = (state, actions) => key => {
  if (!setup) {
    actions.commit(JSON.parse(localStorage.getItem(key)))
    setup = true
  } else localStorage.setItem(key, JSON.stringify(state))
}

app({
  state: {
    count: 0,
  },
  actions: {
    commit: () => state => state,
    up: state => _ => ({ count: state.count + 1 })
  },
  view: (state, actions) => main([
    Tardis(state, actions)('hyperapp-state'),
    h1(state.count),
    button({ onclick: actions.up }, 'Increment'),
  ])
})
```

I'm still not sure if I prefer this way to the good old `init` (yet) which sure was convenient.. but it has got me experimenting with different component patterns and as you can see, you can get quite a lot done just in the view.

**Comment by JorgeBucaran** [comment]
@leifoolsen What about this?

```js
const state = JSON.parse(localStorage.getItem(key))

const { getState } = app({
  state,
  actions: {
    getState: state => state
  }
})

setInterval(() => saveState(getState()), 1000)
```

**Comment by lukejacksonn** [comment]
The first one is not really an option as it is not a solution to the problem and not all the code is there to actually make it work without breaking. So not really a fair code comparison either.

In the second soliution.. what does the `subscribe` function look like and what is it injecting? What about the `key` variable? Could create multiple of these or insert it at various levels in the state tree? This solution conflicts with modules too.

**Comment by JorgeBucaran** [comment]
@lukejacksonn You are right. The solution is to remove modules.
Modules are convenient, but they introduce a problem: now you have two ways to define state and actions. (edited)


[13:04] 
How is this a problem? Well, it makes it very difficult to wrap your state and actions outside the app() call.

Without modules, we can assemble our state outside the app call (if there is a need) and only then `app({ state })`.

The snippet above using localStorage, is a good example. Your pointed what happens if there is nothing in the store and you were right. And how do I access the state injected by modules?

We need to either bring init back or simply remove modules leaving state assembly completely up to the user.

**Comment by lukejacksonn** [comment]
We are doing this all to accommodate a more complicated solution to an already solved problem. Not just solved.. but solved simply and requires zero changes to any core features. Let us look at the actual copy/paste-able solution that works *today* in any hyperapp.

Notice the solution **does not** use modules but it also does not exclude their use just because it is the only way you can find to to make it work any other way.

Above app:
```js
let setup = false
const Tardis = ({ key, state, action }) => {
  if (!setup) {
    action(JSON.parse(localStorage.getItem(key)))
    setup = true
  } else localStorage.setItem(key, JSON.stringify(state))
}
```
In actions:
```js
tardis: () => state => state
```
In view:
```js
Tardis({
  key: 'hyperapp-state',
  state,
  action: actions.tardis,
})
```

If you are indeed intending on moving modules then people are going to have to wire up actions manually themselves. So importing this feature from a package on npm somewhere is still going to be as easy or easier than importing your solutions.

This is my main issue btw.. nothing easy easy to share in hyperapp apps. I always have tyo re-invent the wheel. Modules helped that a bit and in most cases you can get away with adding a very simple `module` and a `component` like the router.

```
import router, { Route, Link } from '@hyperapp/router'
```

Not all of us have the liberty of just being able to add/remove features because they aren't compatible with the problem space. So we work within the existing constraints. I have yet to hear why `init` and a `component` approach is actually so bad. Until then I will keep building components as they feel simpler and more re-usable that other solutions that have been proposed.

**Comment by leifoolsen** [comment]
Thank you all for helpful answers.
This is what I ended up with:
```js
  const dispatch = app({
    state,
    actions,
    view
  });
  window.addEventListener('beforeunload', () => dispatch.storeState());
```

**Comment by JorgeBucaran** [comment]
@leifoolsen I removed modules from master and will publish later.

This should be the way forward:

```js
const actions = app({
  state: JSON.parse(localStorage.getItem(key)),
  view,
  actions
})

window.addEventListener('beforeunload', () => dispatch.storeState())
```

And eventually, we may have a dedicated solution for subscriptions, like a function or functions run for each state update that would help you with the storeState step.

Thanks for bearing with us! 🙇

**Comment by leifoolsen** [comment]
Thanks again for helpful comments and answers. I now have a working demo application built with Hyperapp 0.16.0 (just waiting for the router to catch up), with the following features:
* Webpack3 with Node Express middleware and HMR
* PostCSS/cssnext/css-modules

Repo here: https://github.com/leifoolsen/webpack2-boilerplate
