### ISSUE TITLE
Inaccurate description

### ISSUE THREAD

**Issue by beenotung** [hyperapp/hyperapp#460]
The description said the library is 1KB, but the code is indeed 7.62 KB.
Even the minified dist version is 3.2K

**Comment by olstenlarck** [comment]
It's inaccurate from day one, but sadly no one cares and keep promoting it as such - no matter that it even never been 1kb.

**Comment by leeoniya** [comment]
the gzipped size is 1.35KB, so it's close-ish. most js libs now advertise gzipped size, which would be the size over the wire in the majority of real-world deployments.

**Comment by okwolf** [comment]
The current minified, gzipped bundle from `master` is 1427 bytes or 1.39 KB.

This will often be summarized as 1 KB, depending on what rounding rules you are using.

**Comment by JorgeBucaran** [comment]
@beenotung @olstenlarck I don't know in other programming languages ecosystems, but in JavaScript land, whenever you see "x.xKB library", it universally refers to the library **minified and gzipped**. For example, preact which is currently 3.5KB, uncompressed is 8.7KB and 20 KB unminified.

The current size of Hyperapp is 1427~1408 B or 1.39~1.37 KB, depending on how you compress it: gzip, zopfli, brotli, etc. To calculate the KB size, you divide the number of bytes by 1024, which is the number of bytes in 1 [Kilobyte](https://en.wikipedia.org/wiki/Kilobyte).

<pre>
<b>1427B</b> / 1024B = <b>1.39KB</b>
</pre>

Check out BundlePhobia to see how large a library is, instead of calculating all of this yourself.

For example: https://bundlephobia.com/result?p=hyperapp

<img width="1065" alt="screen shot 2017-11-19 at 11 01 23" src="https://user-images.githubusercontent.com/56996/32986588-1cfe5a6a-cd19-11e7-9c1f-e2f0e2c39c9a.png">

**Comment by JorgeBucaran** [comment]
> @olstenlarck  Yup. It's inaccurate from day one, but sadly no one cares and keep promoting it as such - no matter that it even never ever been 1kb.

Don't misinform other people. As you follow the same convention on [your own projects](https://github.com/olstenlarck/gibon), you can't claim ignorance either.

<img width="717" alt="screen shot 2017-11-19 at 11 10 40" src="https://user-images.githubusercontent.com/56996/32986659-57c819d2-cd1a-11e7-8484-21259e44dcdc.png">
<img width="880" alt="screen shot 2017-11-19 at 11 10 56" src="https://user-images.githubusercontent.com/56996/32986658-57a1aef0-cd1a-11e7-94ad-9e0de607b2ed.png">

Although it seems that particular one is due for an update. The only true thing from day one is you trolling this organization.
