### ISSUE TITLE
How is hyperapp related to picodom?

### ISSUE THREAD

**Issue by fskreuz** [hyperapp/hyperapp#471]
I happen to stumble across both frameworks and notice something funny. The syntax, as well as contributors are the same, but neither is dependent on the other and neither mentions the other as well. 🤔 

How are these two frameworks related? Are they part of a suite of tools? What other frameworks are there that tie in to either? Do they work the same?

**Comment by zaceno** [comment]
Basically: hyperapp came first, being a tiny vdom+state framework implementing the elm architecture. As the API was discussed and being developed on slack, some of us wanted to try out some more divergent ideas for  state management / API. Rather than all of us copy& pasting hyperapp s vdom into our own projects (certainly doable, since it's so tiny) @JorgeBucaran published just the vdom part of hyperapp as picodom, for us (and anyone) to play with. 

One of hyperapps design goal was and still is zero dependencies. So while it might have made sense to make hyperapp depend on picodom, now that it was broken out, we let picodom lead its own separate life. It is still quite close to hyperapp, but may diverge further in the future.

**Comment by JorgeBucaran** [comment]
@fskreuz Exactly what @zaceno said! 👋😄

**Comment by JorgeBucaran** [comment]
> What other frameworks are there that tie in to either? 

There are no other frameworks as far as I am concerned. The ecosystem is very simple. Both projects have interesting stuff going on for them. 🎉
