### ISSUE TITLE
Should Slices support Array type?

### ISSUE THREAD

**Issue by sam-chuang** [hyperapp/hyperapp#472]
From the [Slices doc](https://github.com/hyperapp/hyperapp/blob/master/docs/slices.md), it doesn't mentioned supported type, so I tried to use Array with it, then I got error, refer to [test code here](https://repl.it/@randomness/hyperapp-array-slice)

From the [merge function in src](https://github.com/hyperapp/hyperapp/blob/master/src/index.js#L35), it seems that Slices only support object type.

**Comment by SkaterDad** [comment]
@sam-chuang You are correct, only objects are supported.  This is because state slices are intended to reduce boilerplate when updating deeply nested object keys.  It's a similar concept to Redux/Vuex modules/namespacing.

If you want your state to have an array, the action modifying it needs to be at the same level in the actions tree, but with a different name.

```js
import { app, h } from 'hyperapp'

const appActions = app({
  state: {
    arr: [1, 2, 3]
  },
  actions: {
    addToArr: (num) => (state) => ({ arr: [...state.arr, num] })
  },
  view: (state) => h('pre', null, JSON.stringify(state, null, 2))
})

appActions.addToArr(4)
```

**Comment by JorgeBucaran** [comment]
@sam-chuang Yep, slices only support object types.

**Comment by dmitry-vakhnenko** [comment]
How it looks with model entry?

**Comment by JorgeBucaran** [comment]
@dmitry-vakhnenko Good question, if modules are passed, then this loses all its value, although, even if that doesn't go through, I don't think I'd want to go back to any-type-state.
