### ISSUE TITLE
What about using ES6 features?

### ISSUE THREAD

**Issue by dmitry-vakhnenko** [hyperapp/hyperapp#486]
http://node.green/ (99% from v6.12.2 to 10.0.0 nightly)
https://caniuse.com/#search=es6 (~85% features of es6 are supported in most popular browsers)

**pros**
  - reduce size
  - performance (in any cases)
  - can be transpiled if it really necessary (old browsers)

**cons**
 - in some envs we should use `transpilation step` (but it needs for some external libs anyway)

Please :+1:  if you like it and :-1: otherwise.

**Comment by JorgeBucaran** [comment]
@dmitry-vakhnenko What ES6 features do you want to use? 

Hyperapp is already written in ES6 because we are using ES module syntax, and as such, you can use it as an [ES module](https://jakearchibald.com/2017/es-modules-in-browsers/) out of the box without compilation.  

Hyperapp also works on IE10 and according to @Alber70g on IE9 too, again no compilation needed. 

Rewriting the library in ES6 would be fun, but would force me to introduce a compile step, which is unnecessary complexity and I don't want to depend on that. I know most people compile their apps anyway, I do too, but those are actual apps. Hyperapp on the other hand is so simple, you can use it as is.


> reduce size
Only if we distribute the minified source code, but that would be too limiting. I don't know of any libraries that do that.

> performance (in any cases)
Which cases?

> can be transpiled if it really necessary (old browsers)

It needs to be transpiled for us so that our CDN bundles are compatible with older browsers. I already explained why I don't want to introduce a compile step above.

Now, the good news is that someday I'll be able to ship hyperapp using only ES6. That will be the day when we decide to stop supporting IE11. 🎉

**Comment by dmitry-vakhnenko** [comment]
array functions fastest > functions(){} because they don't create context
and
https://jsperf.com/spread-vs-arguments/1

**Comment by JorgeBucaran** [comment]
@dmitry-vakhnenko 

- spread-vs-arguments: same on firefox, spread wins on chrome. However, this is really JSX fault. See #462.
<img width="987" alt="screen shot 2017-12-10 at 22 46 46" src="https://user-images.githubusercontent.com/56996/33805425-02f5194e-ddfc-11e7-9aef-797cd4fd2de3.png">

- merge-vs-assign: merge was faster on firefox and in chrome because your test case was wrong, `Object.assign(a,b)` mutates `a`. Our merge is immutable, so it's like `Object.assign({}, a, b)`.

<img width="982" alt="screen shot 2017-12-10 at 22 45 10" src="https://user-images.githubusercontent.com/56996/33805412-c6cf72ca-ddfb-11e7-9f6d-4d06fa71db61.png">
<img width="965" alt="screen shot 2017-12-10 at 22 51 18" src="https://user-images.githubusercontent.com/56996/33805461-bd9f7a1e-ddfc-11e7-88a6-39cf5e4dc90c.png">

**Comment by dmitry-vakhnenko** [comment]
Iam sorry. thanks

**Comment by JorgeBucaran** [comment]
Let me clarify: I would love to rewrite hyperapp in ES6 and say to hell with old browser support, but there's more to lose than to win by doing it. So, I'm going to wait until the day we can and then do it! 😄
