### ISSUE TITLE
Remove ability to defer node removal inside onremove

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#496]
The idea is to make onremove behave like ondestroy and remove the current onremove functionality. 

See also: https://github.com/picodom/picodom/issues/68

**Comment by zaceno** [comment]
Hos do you propose one does onremove transitions in this case?

**Comment by JorgeBucaran** [comment]
@zaceno Well, it's not perfect right? See also: https://github.com/hyperapp/hyperapp/pull/497 I merged onremove/ondestroy and kept both functionalities.

**Comment by zaceno** [comment]
@JorgeBucaran what's not perfect about https://codepen.io/zaceno/pen/QOYOZd ? The only problem with it is the amount of code needed to make it work. (And perhaps some unrelated wierdness on chrome+windows I haven't managed to look into yet) -- but if you remove the ability to defer element removal in `onremove` then transitions become impossible *entirely*. I don't see the win.

>  See also: #497 I merged onremove/ondestroy and kept both functionalities.

I don't understand? In that PR it looks like you're *keeping* the abiltiy to defer removal of the element. Which is it? 

(Disclaimer, I haven't really followed the `ondestroy`  topic since it hasn't been a concern for me)

**Comment by JorgeBucaran** [comment]
@zaceno Both functionalities were kept in the PR. Sorry for the confusion, this issue was about discussing removing the functionality of onremove altogether, which I now see was a bad idea even to bring up.

**Comment by zaceno** [comment]
@JorgeBucaran Ah, ok, I'm follwing now 😄 , I think...

 So "both functionalities" refers to:

- ability to defer element removal
- recursive calling of onremove handlers in child nodes

... and we're going to have them both in 1.0.

Correct?

**Comment by JorgeBucaran** [comment]
@zaceno Yes, that's right. 👍
