### ISSUE TITLE
Rewrite patch algo / improve diffing performance

### ISSUE THREAD

**Issue by jorgebucaran** [hyperapp/hyperapp#499]
I want to rewrite patch to incorporate some prefix/suffix trimming techniques as described in the first link posted below.

Hyperapp unkeyed and keyed fares relatively well according to [js-framework-benchmarks](https://github.com/krausest/js-framework-benchmark) (arguably the best benchmark out there and by far), but we could do a bit better and still get away with our 1 KB proposition.

- https://github.com/hyperapp/hyperapp/issues/216#issuecomment-314051357
- https://github.com/yelouafi/petit-dom/blob/master/src/vdom.js

**Comment by leeoniya** [comment]
there's a non-zero chance that we'll absorb uibench's 4 "worst case" scenarios [1]. prefix/suffix checks will help some of these, but not all.

all of uibench is actually a great testing/perf regression tool.

[1] https://github.com/localvoid/uibench-base/blob/efacae672bbf4133360a928305876ee1de643e64/lib/uibench.ts#L302-L319

**Comment by JorgeBucaran** [comment]
@leeoniya Can you elaborate? What am I looking at? 😄

**Comment by leeoniya** [comment]
the public page is here: https://localvoid.github.io/uibench/

what the linked code does should be fairly obvious from the function names.

**Comment by JorgeBucaran** [comment]
@leeoniya Thanks. I've merged your comments into the same post. I don't want to derail this issue and if possible keep the convo on point.

**Comment by okwolf** [comment]
The core VDOM (Picodom) looks pretty close to vanilla in the [latest js-framework-benchmark](http://www.stefankrause.net/js-frameworks-benchmark7/table.html).

What I find really interesting is where Hyperapp underperforms Picodom:

![screen shot 2017-12-16 at 23 11 13](https://user-images.githubusercontent.com/3735164/34077339-94742cde-e2b6-11e7-9336-d12ec1d4a8af.png)

By a factor of 3x in some cases! 😮

**Comment by JorgeBucaran** [comment]
@okwolf That's a different library: https://github.com/hville/pico-dom, the picodom I wrote is not on that list.

**Comment by okwolf** [comment]
@JorgeBucaran oh. I guess there can never be too many libraries with similar names 😕 

Well, I think comparing the performance of the _real_ Picodom library with Hyperapp might still be a worthwhile experiment.

**Comment by okwolf** [comment]
@JorgeBucaran have you done any more research on this topic yet?

I was browsing through the [VDOM for Elm](https://github.com/elm-lang/virtual-dom/blob/2e4f74331d010c7199d803bd9a5c244e1939ef55/src/Native/VirtualDom.js#L835) and thinking of you.

**Comment by JorgeBucaran** [comment]
@okwolf A little bit. I have a simplified (still not quite working) version of [this](https://github.com/ivijs/ivi/blob/2c81ead934b9128e092cc2a5ef2d3cabc73cb5dd/packages/ivi/src/vdom/implementation.ts#L1366-L1593). It adds like 300 bytes, but makes Hyperapp as fast as ivi. 🙄

**Comment by joshrtay** [comment]
solid diff library: https://github.com/ashaffer/dift

**Comment by dmitry-vakhnenko** [comment]
Any updates?

**Comment by JorgeBucaran** [comment]
Yes, but nothing concrete yet. I am making progress, just very slowly. I think we'll see a newly improved diff in 2.0 or after, in a few months.

My intention is not to introduce a new faster algorithm at the expense of making the code unreadable and complicated. So, not only I need to understand the problem and the solution very well, but I need to document it well so that everyone can understand it.

**Comment by jorgebucaran** [comment]
We need to start saving the DOM instance in the vnodes for easier access later, this could even save bytes. This is also what ivi, nerv, (possibly petit-dom too) do if I am not mistaken.

**Comment by localvoid** [comment]
All fastest vdom implementations are storing reference to a DOM node in a vnode object or create one more tree that contains references to a vnode and DOM node. They don't read anything from DOM nodes, DOM api is used only for mutations.

Storing reference to a DOM node in a vnode object has obvious advantage that you won't need to instantiate many additional objects, but there is also a drawback that you won't be able to reuse vnodes, for example, to hoist static trees. It is possible to detect collisions and clone vnodes, but in my opinion it isn't worth it, because there are too many edge cases.

React is using immutable vnodes and has a plugin[1] that detects static subtrees and hoists them to improve performance.

Vue2 is using mutable vnodes[2], so I guess that it doesn't cause any problems in practice and it is worth it. Developers just should be aware of this limitations[3].

1. https://babeljs.io/docs/plugins/transform-react-constant-elements/
2. https://github.com/vuejs/vue/blob/6bc75cacb72c0cc7f3d1041b5d9ff447ac2f5f69/src/core/vdom/vnode.js#L8
3. https://vuejs.org/v2/guide/render-function.html#Constraints

**Comment by jorgebucaran** [comment]
@localvoid Thank you for your incredible help. When you refer to hoist static trees do you mean something like memoizing a view that must return the same virtual DOM tree if the state hasn't changed (in Hyperapp the state is immutable, so it's moderately "easyW to memoize views).

**Comment by localvoid** [comment]
By hoisting static trees I mean that you can hoist vnodes that doesn't contain any dynamic content from render functions and then reuse it.

For example, here is a component that consists of two spans: one is dynamic and another one is static.

```jsx
function Component(props) {
  return (
    <div>
      <span>{props.text}</span>
      <span>Static Text</span>
    </div>
  );
}
```

In React it is possible to hoist span that doesn't change and reuse it each time component is rendered. And `transform-react-constant-elements` plugin can automatically hoist such static subtrees.

```jsx
const staticSpan = <span>Static Text</span>;

function Component(props) {
  return (
    <div>
      <span>{props.text}</span>
      {staticSpan}
    </div>
  );
}
```

In Vue2 it will break because `staticSpan` will contain reference to a DOM node, and when you create two instances of this component, second one will overwrite reference from the previous one.

In my opinion, it is easy to optimize static subtrees just by wrapping them into components and it is better to improve overall performance by using mutable vnodes, but there are people who disagree.

**Comment by okwolf** [comment]
Based on [this tweet](https://twitter.com/JorgeBucaran/status/1015649320530374656) I'm guessing we can close this issue once 2.0 ships?

**Comment by jorgebucaran** [comment]
@okwolf Not yet, there's still another big optimization left to do.

**Comment by jorgebucaran** [comment]
For now, I'll leave this here:

![superfine](https://user-images.githubusercontent.com/56996/42416263-ee50cec2-82a4-11e8-99fd-021a23e34f05.jpg)

**Comment by poppinlp** [comment]
Nice job!! Can't wait~ :)

**Comment by jorgebucaran** [comment]
Closing as I'm tracking this particular performance optimization as part of the VDOM rewrite that will ship with V2 now.
