### ISSUE TITLE
Removal of item re-renders the whole list instead of removing a particular node

### ISSUE THREAD

**Issue by brijeshb42** [hyperapp/hyperapp#515]
Here's a gif from Firefox devtools

![hyperapp](https://user-images.githubusercontent.com/717550/34429368-621b24c4-ec7d-11e7-97f5-7682a8683944.gif)

The code that I used is [here](https://codepen-4ede0.firebaseapp.com/gist/93a82e5b1a05322b4b5e8fe1d166f87a)

I have taken care of generating unique ids for each list item. Ideally, removal of an item from array should just remove the corresponding node instead of re-rendering the whole list.

**Comment by JorgeBucaran** [comment]
Is this related to https://github.com/hyperapp/hyperapp/issues/499? If so, I'd prefer to track it there. This is not a huge problem, but it's something I definitely want to tackle in 2018.

**Comment by JorgeBucaran** [comment]
@brijeshb42 Nevermind, I just remembered this is something else. The algo is just reattaching the event listeners, the DOM nodes **are not** recreated.

The reason the nodes are flashing is because the algorithm is changing their order with `element.insertBefore` inside [patch](https://github.com/hyperapp/hyperapp/blob/c9aed6efdf6735683db71ebf7b7b6eae7e0c2cad/src/index.js#L217-L306).

**Comment by JorgeBucaran** [comment]
Closing in favor of #499.
