### ISSUE TITLE
Allow a custom merge method

### ISSUE THREAD

**Issue by titouancreach** [hyperapp/hyperapp#532]
Currently, when a action return a new state, this one is merged with the previous state. That make the object "state" to grow but never shrink. I would imagine this behavior to be configurable with a pure function. where the default would be:

```javascript
const mergeState = (previousState, newState) => ({...previousState, ...newState});
```

To have the same behavior as redux for example, we can use this function
```javascript
const mergeState = (previousState, newState) => newState;
```

**Comment by JorgeBucaran** [comment]
@titouancreach How would that look in a simple app and why would I want my state to shrink?

**Comment by titouancreach** [comment]
The first example that would come to my mind would be: I want to create a simple router, I would be able to do:

```javascript
import defaultStatePageFooBar from '...';

actions: {
  goToPageFooBar: (state) => defaultStatePageFooBar
}
```

I find the second `mergeState` more functional and more natural because you don't hide a "merge" to the user.

**Comment by JorgeBucaran** [comment]
@tiaanduplessis And how would that look like on your app?

**Comment by titouancreach** [comment]
You specify the merge method in the constructor as an optional parameter:

```javascript
app(state, actions, view, document.body, mergeState);
```

**Comment by whaaaley** [comment]
I like the idea of non-merged state. I know merged state has it's own pros, but merging doesn't really help me with my own apps.

If I have some state like this and and I want to update the state.

```
// initial
{
  foo: 'bar',
  bar: 'baz'
}

// now i want this
{
  foo: 'ooga booga'
}
```

I won't be able to. I'd have to set `bar` to `null` myself to denote that it's "removed".

```
// initial
{
  foo: 'bar',
  bar: 'baz'
}

// now i want this
{
  foo: 'ooga booga',
  bar: null
}```

It's not a "con" per se. It's just a way I would prefer to build my apps. Imo, when being able to replace a state object "wholesale" like this, is easier to read and less to code.

**Comment by JorgeBucaran** [comment]
Why would anyone want this `{ foo: 'ooga booga' }`?

**Comment by okwolf** [comment]
The current state update approach in Hyperapp reminds me of [updating records in Elm](http://elm-lang.org/docs/records#updating-records) or `Object.assign(state, { key: value })`/`{ ...state, key: value }` from ES 6, but without the boilerplate of bringing in the previous state values.

This is by far the most common use case, and the only one I've used in [reducers for Redux](https://redux.js.org/docs/recipes/UsingObjectSpreadOperator.html).

**Comment by titouancreach** [comment]
I understand the point of view. I think if we only "update" record (update value in) we should not be able to create new keys.

For example: 
```javascript
const state = {
  count: 0
};

const actions = {
  myAction: () => state => ({ foo: 'foo' });
};

```
Should not be possible. I can possibly be a typo

```javascript
const actions = {
  myAction: () => state => ({ coount: 'foo' });
};

```

Then, I would namespace the actions:

```javascript
const state = {
  counter: {
    value: 0 // since state can only be object
  }
};

const actions = {
  counter: {
    myAction: () => state => ({ value: state.value + 1 });
  }
};

```
In this case, it won't be possible to create a key a top level without the possibility to remove it. Actions are also more "local" since they work with a part of the state and not the full state. It will encourage to make more little actions.

**Comment by whaaaley** [comment]
> Why do you want this { foo: 'ooga booga' }? 🤔

Maybe I'm listing out all my state in one of my slices. Of course I could add a condition to check for null/undefined here, but why bother if I could just update my state to not include those?

```js
const list = state => {
  const result = []
  for (let key in state) {
    result.push(h('div', null, `${key}: ${state[key]}`))
  }
  return result
}
```

Maybe I just want to bulk update all of my state at once and get a fresh start where a few or none of my state props are the same, so my views don't get funky. Like when retrieving data from an endpoint or user input.

```js
// i started with this
{
  foo: 'one',
  bar: 'two',
  baz: 'three'
}

// now i want this
{
  abc: 'seventy two',
  xyz: 'eighty nine'
}
```

Which could change the way the view is rendered.

```js
if (state[key_based_off_of_user_input_here] && state[key_based_off_of_user_input_here] === 'two') {
  // do code
}
```

I've been meaning to create an example that better demonstrates this. The reason I haven't is because this is more of a preference rather than something that has a ton of functional gain. I just enjoy replacing state completely while developing to be honest. I do this in my test apps with my pocket project. If it doesn't get added I wouldn't be terribly heartbroken, but I would enjoy it if it did.

**Comment by vdsabev** [comment]
Most people are used to spread-merging `{ ...previousState, ...newState }` from Redux. I like the deep merge, but wanted the option to change the function as well, which is why I implemented it in [Derpy](https://github.com/vdsabev/derpy#shallow-merge).

I think if we keep adding parameters to `app` we might wake up with 7 or 9 someday soon 😆
How about something more future proof like:
```js
app(state, actions, view, document.body, { merge: Object.assign });
```

**Comment by JorgeBucaran** [comment]
I don't consider this to be remotely critical, but I would reconsider if it was. However, none of the answers has been able to justify adding this, so I am gonna go with @okwolf's and avoid us option paralysis.

> This is by far the most common use case, and the only one I've used in reducers for Redux.
