### ISSUE TITLE
how to prevent "no state change view render func"     execute

### ISSUE THREAD

**Issue by hongmomanu** [hyperapp/hyperapp#540]
my english is poor  ,the case is 
when i have a main view like:
```
export const view = (state, actions) =>
  <div class='container'>
    <MyHeader />
    <h1>{state.count}</h1>
    <AddButton actions={actions} />
    <SubButton actions={actions} />
  </div>

export const MyHeader = () =>{
  console.log('MyHeader');
  return <header>
        <h2>hyperapp is cool  </h2>
     </header>
}

```
if i use action to  change the count state , the 'MyHeader' will always execute , is it reasonable？ if it is not ,how to prevent?

**Comment by JorgeBucaran** [comment]
@hongmomanu Yes, it is reasonable! To render your app, we run your view function to produce a vnode tree and consume this object to literally "patch" the DOM, so every time your state changes, we need to calculate a new vnode tree to update the page.

**Comment by JorgeBucaran** [comment]
@hongmomanu It will not as much as you think. This is exactly how React and other VDOM-based frameworks work. The performance cost is in the diffing of vnode trees produced from a previous state and the current state, yet, it's still fast enough to update 10,000 nodes within ~200ms. If your app is consuming more than 100K, then the problem is your app. 😉

**Comment by hongmomanu** [comment]
@JorgeBucaran tks again,i get it! by the way, your lib is amazing!  i will close the issues.

**Comment by JorgeBucaran** [comment]
Awesome and thanks! 🎉
