### ISSUE TITLE
@hyperapp namespace for the main library?

### ISSUE THREAD

**Issue by rhbecker** [hyperapp/hyperapp#563]
Have you yet considered putting this "core" hyperapp library into the @hyperapp [namespace](https://docs.npmjs.com/getting-started/scoped-packages)? e.g. @hyperapp/hyperapp or @hyperapp/core or whatever?

I appreciate that html, logger, and router libraries are collected together, and would find it convenient to have this library similarly situated.

**Comment by JorgeBucaran** [comment]
> @rhbecker ...would find it convenient to have this library similarly situated.

No, I haven't considered it, but I am curious how and why would you find it convenient?

```
npm i hyperapp
```

vs

```
npm i @hyperapp/hyperapp
```

**Comment by okwolf** [comment]
The only argument I see for this would be consistent naming, and I don't think that's a strong enough reason.

Angular does have `@angular/core`, but React sticks with just plain old `react`.

**Comment by rhbecker** [comment]
I find package scoping convenient when navigating the file system.

e.g. here's my hello world's node_modules directory:

![scoped](https://user-images.githubusercontent.com/224732/35201116-490cf59a-fecd-11e7-969f-cc6315862e30.png)

**Comment by JorgeBucaran** [comment]
@rhbecker Hmm, yeah I see the pain point. I would rather change `@hyperapp/xxx` packages to `hyperapp-xxx` instead of changing how Hyperapp is installed, but then how is people going to tell the difference between "official" packages and non-official ones? 🤔

**Comment by rhbecker** [comment]
It's certainly not a giant pain point to leave it as-is, but I'm curious why you're reluctant. Is it just that `npm i @hyperapp/hyperapp` is more to type?

**Comment by rhbecker** [comment]
(Regardless, I will not be offended if you close, won't fix.)

**Comment by JorgeBucaran** [comment]
@rhbecker Because not everyone is familiar with npm's scoped packages. Also, I feel it defeats the ethos of Hyperapp. I set out to create a simple framework but somehow ended up using npm scope packages. It begs the question: what are you building that is so complex that can't work as a plain old npm package?

Other reasons include more typing, and the waste of time and resources that is: republishing, asking everyone to update their `package.json`'s, tell npm to transfer `hyperapp` to `@hyperapp/core` (or ask them to decommission the then-obsolete module), etc.

Thanks for asking, but I think I want to leave things as is this time! 🙏

**Comment by rhbecker** [comment]
understood ... thanks for letting me peek into your thinking.

**Comment by frenzzy** [comment]
Can't we just publish Hyperapp as `hyperapp`, `@hyperapp/core` and `@hyperapp/hyperapp` together?) Anyone can choose what he wants...
