### ISSUE TITLE
Compile JSX right into virtual node objects avoiding `h` function

### ISSUE THREAD

**Issue by frenzzy** [hyperapp/hyperapp#564]
There are an idea to avoid using [`h`](https://github.com/hyperapp/hyperapp/blob/1.0.2/docs/concepts/vnodes.md) in favor of compilation step which will do the same work.
_Compile JSX:_
```js
const view = (state, actions) => (
  <main>
    <h1>{state.count}</h1>
    <button onclick={actions.down}>-</button>
    <button onclick={actions.up}>+</button>
  </main>
)
```
_to:_
```js
const view = (state, actions) => ({
  name: 'main',
  props: {},
  children: [
    { name: 'h1', props: {}, children: [state.count] },
    { name: 'button', props: { onclick: actions.down }, children: ['-'] },
    { name: 'button', props: { onclick: actions.up }, children: ['+'] }
  ]
})
```
Potentially the app should work faster this way because each function call requires additional computing resources. Also `h` which is still necessary for JSX haters could be tree shakied from your build.

Possible future improvements: adopt [babel-plugin-transform-react-constant-elements](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements) to speedup the app even more:
```js
const h1 = { name: 'h1', props: {}, children: ['Static content'] }
const view = (state, actions) => h1
```

Can anyone foresee potential pitfalls?

**Comment by vdsabev** [comment]
I started some work on a `jsx-to-object` compiler in https://github.com/vdsabev/jsx-to-object/pull/1/files#diff-1dd241c4cd3fd1dd89c570cee98b79dd but got held up with an Esprima issue parsing the `...` spread operator.

If anyone has ideas or suggestions on an alternative parser that supports JSX, I'd be happy to drop Esprima and use something else instead 😅

**Comment by frenzzy** [comment]
@vdsabev have you tried [babylon](https://github.com/babel/babel/tree/master/packages/babylon) parser? Or could it be implemented as a babel plugin?

**Comment by vdsabev** [comment]
Great suggestions, I'll try when I get the time!

I started with acorn first (on which babylon is based), but decided to switch to esprima (don't remember why anymore). From what I've read recently, babylon supports all the use cases I need, and has even had contributions from the TypeScript team.

I might write a babel plugin on top of `jsx-to-object`, the goal is to have it as a standalone utility that you can use from a CLI, gulp, whatever, so as to not strictly depend on babel. I don't have experience doing anything like that, so it'll be a learning opportunity.

In any case, this is not going to be hyperapp-specific at all. Potentially, hyperapp could remove the dependency on the `h` function, but I don't think that uses up that many bytes 😄

**Comment by lukejacksonn** [comment]
If you figure this out.. I would like to do the same thing for https://github.com/lukejacksonn/ijk so that you have the option of precompiling views of that type.

**Comment by kenOfYugen** [comment]
If I understand correctly, do you mean to achieve something like what [prepack does](https://prepack.io/repl.html#GYVwdgxgLglg9mABACwBRgIYFsCmAaRABwCc5CBnASkQG8AoRRANw2MTDgBMcHnXFiOclEQBeRAG0AurxZsIyGABtOgpOOmz+SnGADmUZGMSs9IXGCjkAdDv2G6vAO6KdiVHYPIAtN8QA+RAAmakFha0IQcjRTc10rCU9DKUpHRhdlHHcwqFtdL2p6RkYYYHcAQWJiDABPaxhySuqa1HQuLPEciLJUSj7C3mLEYDg2D3zDYw5uPPtkAG5EJJ9vRYGhoa7I6LbuRInkFMHigF9jk8QcJXIs0vdprIBCcTAQJSVEADJP9nbEZ-EUGIICy31+3H+onEwAw1xw6w2CmUql0ESiaAeqSGZ0YZ14gigIGISCgNUIODgZUwuDEUMQACJQJBYAh6ccAPzsbA4VAkMjkRAAH0FtBOBCRKjUWOKAC5aMchtScHKlXgFcU+RQ5ZqBcLRWqNsUJSiwHLjWp1Wc8RAEMJEMIMFAOvLGDbwFA5QAGOjW20iDDQeBgAXiIqIThwJymvhKEFiQIOp3x9w0RBuyxyxM4azpkR+FixrInSgGxAgQhygtx0QJqCOjqBVCp3OZutOnNwd2IADUMbjxZ9dBtwZETBgOCcxlQWYIAZZweoNd4aHpnBgTHpBBoYskxxXyAAjJv9fa29ncyW96h6QAjEBQKCsreIBAQJQwCAAazlvWTc6DNgRlGqAHtQO70oAyAT0peQwrneD5PrQL6QO+X4-ougT-ra1jliBYEEPS3bQbwRyMEOtpwDothwHoqBjhO05nrOga2n08xAA)?

**Comment by JorgeBucaran** [comment]
@kenOfYugen No, I don't think so, nope. The idea is:

JSX:

```jsx
//@jsx h
<div id="ok">OK</div>
```

babel+babel-plugin-transform-react-jsx:

```jsx
h("div", { id: "ok" }, "OK")
```

This proposal:
```jsx
{
  name: "div",
  props: { id: "ok" },
  children: "OK"
}
```

**Comment by kenOfYugen** [comment]
@JorgeBucaran OK I see, I got confused.
Since we are talking tooling too, why not [Sweet.js](https://www.sweetjs.org/) for this task? Have you considered it @vdsabev? Something like [this](https://github.com/jlongster/jsx-reader).

I am a `jsx` hater 😆 , but would love to try to create macros for `@hyperapp/html` in order to get rid of the dependency and `h` altogether (and save those precious ~200b for future optimizations).

**Comment by JorgeBucaran** [comment]
@kenOfYugen I think the net result would be a lot more bytes because you would have raw nodes all over the place. Food for thought. 🍲 😉

**Comment by kenOfYugen** [comment]
@JorgeBucaran That is correct.
In the case of raw nodes, I believe they gzip/brotli wonderfully. The 'hello world' difference is ~161b vs ~169b gziped after the closure compiler for the `h` vs raw nodes versions respectively. I don' t have any insight on how well it scales though. I am not aware of any real-use benchmarks either.

**Comment by vdsabev** [comment]
I just found https://github.com/calebmer/node_modules/tree/master/babel-plugin-transform-jsx
This should serve as a good starting point. From what I saw it doesn't allow customizing the output out of the box, e.g. `{ type, props, children }` instead of `{ elementName, attributes, children }`, but it could work with some tweaking,

**Comment by sergey-shpak** [comment]
@vdsabev @JorgeBucaran @frenzzy 
hey, some ~~dirty~~ small workaround for `babel-plugin-transform-jsx` (.babelrc):
```json
"plugins": [
  ["transform-jsx", {
   "function": "(n=>({name:n.elementName,props:n.attributes,children:n.children || []}))",
   "useVariables": true   
  }],
]
```

and now

```jsx
const Component = props => console.log(props.foo);
export default (state, actions) => <div>
  <Component foo="bar">Some child</Component>
</div>
```

transformed into something like:

```javascript
const Component = props => console.log(props.foo);

(state, actions) => ({
  name: 'div',
  props: {},
  children: [{
    name: Component,
    props: {
      foo: 'bar'
    },
    children: ['Some child']
  }]
});
```
--------------
Looks good, but it doesn't work with hyperapp.
 
`Component` function is not executed, as result it doesn't build nested vNode structures (as ['h' function does](https://github.com/hyperapp/hyperapp/blob/master/src/index.js#L20)) 

It's not possible to create DOM elements from functions and [createElement](https://github.com/hyperapp/hyperapp/blob/master/src/index.js#L155) will fail with something: Couldn't create element from "props => console.log(props.foo)"

Any thoughts?

**Comment by JorgeBucaran** [comment]
> @sergey-shpak Component function is not executed...

Hmm, right, I see. This is a not so obvious limitation, but I think this means what were trying to do is impossible.

**Comment by frenzzy** [comment]
Looks like need to transpile components
```js
<div>
  <Component foo="bar" />baz</Component>
</div>
```
into function call
```js
{
  name: 'div',
  props: {},
  children: [
    Component({ foo: 'bar' }, 'baz')
  ]
}
```

**Comment by zaceno** [comment]
@frenzzy 

```js
{
  name: 'div',
  props: {},
  children: [
    Component({ foo: 'bar' }, ['baz'])
  ]
}
```
... I presume you mean

**Comment by JorgeBucaran** [comment]
@frenzzy There's nothing actionable core can do here. Do you want to close this or do you want to add something else?

**Comment by frenzzy** [comment]
The core might add support for function to be able to use it as a vnode:
```js
{ name, props, children: [
  () => vnode,
  // or
  { name: () => vnode, props, children }
] }
```
but currently I do not see benefit of this.

Let's close this for now. Feel free to add any notes here.

**Comment by SkaterDad** [comment]
So.... I've recently decided to not hate on JSX so hard :laughing: 

The readability is so much higher than nested `h` calls in large view functions, that I really want to convert my main project.  However, the runtime perf costs due to the variable length arguments and extra function calls (`h(Component)`) are hard to swallow.

Today I've been working on getting [babel-plugin-transform-jsx](https://github.com/calebmer/node_modules/tree/master/babel-plugin-transform-jsx) to work with `hyperapp`.

I'm new to Babel transforms, but I managed to get this working!  The transform code was quick & dirty, but I'm really pleased with the results so far :smile: 

As a proof of concept, here is my [recent Lazy Components Codepen demo](https://codepen.io/SkaterDad/pen/jzObVq) run through `babel-plugin-transform-jsx` then my own custom transform:
https://codepen.io/SkaterDad/pen/wmBKbM?editors=0010


Quick rundown:

- Normal HTML elements get transformed to raw VNode objects (thanks to the first plugin).  My plugin renames the properties and changes `children: null` to `children: []` when needed.
- Components & Lazy Components get turned into direct function calls.  No more `h(Component, props, children)`, just `Component(props, children)`.

Next steps:

- Clean up code to ensure I'm only modifying VDOM objects, and just any random object with the properties I'm targeting.
- Package this up with `babel-plugin-transform-jsx` as a dependency, or maybe fork it?
- @jorgebucaran Any interest in this being in the `@hyperapp` NPM scope?
- Performance testing the output against the React JSX transform, and against raw `h` calls.   Should be higher since there are less functions being invoked at runtime.
- Compare compiled bundle sizes of an application

**Comment by jorgebucaran** [comment]
@SkaterDad Sounds amazing. 🎉

**Comment by SkaterDad** [comment]
@jorgebucaran  Thought you might be interested in an update on my progress.  

I've got the babel plugin working pretty well, with 3 modes. 
 * Full optimization mode.  This calls components directly as functions, and turns regular html nodes into objects.  Since `h` is no longer used, you have to be more careful about children which are arrays, but I'm working on solutions.
 * Use `h`, passing multiple children as an array instead of variable arguments like `react-jsx`.
 * Same as above, but automatically add `import { h } from 'hyperapp'` to the files so you don't have to.

The function & module names are configurable, so any compatible vnode library should be okay.

I'll publish it to npm once I'm satisfied with the configuration options & tweak it a bit more.

I've done some benchmarking with interesting, but mixed, results.  As you know, benchmarking is a rabbit-hole where logic goes out the door. :laughing:

In general, the "full optimization" mode performs very well compared to the two "h" modes.  Chrome doesn't care much if the children passed to "h" are an array or multiple arguments, but other browsers seem to prefer the array.  IE11 really loves the optimized version, so I guess function calls are expensive there.

When I have a few hours to kill, I'll try to run `JS Framework Benchmark` with various compilation options to get more formal results.  I just wish it was able to get results for Firefox and Edge also!

I'm also exploring the performance implications of adding "lazy"/"thunk" support to hyperapp, similar to elm's.  Since we have immutable state, our implementation can be similar.   I'm seeing good results so far, and it's not much code, but would like to formally benchmark it before cleaning it up and submitting a PR.  Is that something you're interested in seeing or should I wait for your diffing rewrite?

**Comment by jorgebucaran** [comment]
> @SkaterDad Is that something you're interested in seeing or should I wait for your diffing rewrite?

Awesome! I'd say go for it! I don't think my rewrite would be affected too much anyway. 💯

**Comment by SkaterDad** [comment]
@jorgebucaran  Here's a taste of the JS Framework Bechmark results for lazy/thunks, run in-browser and scientifically clicking around at a steady pace.  I'll run the full automated test again soon.  I ran it last night, but my implementation was wrong, so the results were way too good to be true.  Now that I've fixed it, the results line up with my expectations, showing big wins on partial page updates.  I removed percentages which were within 20% as not being significant.

Test (avg. of 10 runs in browser) | Normal | Thunks | %Improved
-- | -- | -- | --
Create 1000 | 181.74 | 172.12 | 
Update Every 10th - 1000 Nodes | 74.41 | 11.99 | 84%
Swap Rows - 1000 Nodes | 158.17 | 155.36 | 
Create 10,000 Nodes | 1934.625 | 1913.02 | 
Update Every 10th - 10,000 Nodes | 725.5909 | 571.29 | 21%
Swap Rows - 10,000 Nodes | 464.8091 | 300.21 | 35%


Keep Adding 1000 Nodes (only run once) | Normal | Thunks | %Improved
-- | -- | -- | --
Create 1000 | 144.3 | 158.3 | 
Add 1000 to 1000 | 162.6 | 152 | 
Add 1000 to 2000 | 229.6 | 171 | 26%
Add 1000 to 3000 | 228.9 | 181.2 | 21%
Add 1000 to 4000 | 307.1 | 246.7 | 20%
Add 1000 to 5000 | 277 | 207.3 | 25%

 I know it's been said before that generating the tree isn't that expensive, but it can really add up on a large app, or even a small one that has complex logic to generate the VNode tree.  It's a lot faster to do a few strict `===` checks around some components, and generate the new node only if needed. 

I'm look forward to combining these lazy functions with the custom JSX optimizations to get the best of both worlds:  faster node creation, and faster partial updates :sunglasses:   My computer is going to hate me after running all of these variations through JS Framework Benchmark :desktop_computer: :boom: 

The API is pretty ugly right now, so I'll PR once I've thought of a nicer way to use this.

**Comment by SkaterDad** [comment]
Here's an automated run of JS Framework Benchmark.  It was set to 5 iterations, and includes 3 versions of the `hyperapp` test, plus vanilla js.  All keyed.

**hyperapp-v1.2.0-keyed** is the currently submitted implementation.

**hyperapp-not-lazy** and **hyperapp-lazy** use a modified "store.js" which is closer to the elm version.  The big difference is that each data row includes a "selected" boolean, rather than having a single "selected" integer on the model.   The lazy version wraps the `<tr>` generating part of the "Row" component.

![image](https://user-images.githubusercontent.com/13255599/37796224-c1196cda-2de4-11e8-9b28-4b1901bf77d8.png)

Current API (using the benchmark example).
Any VDOM generating function be wrapped this way, not just components:
```jsx

import { h, lazy } from "./hyperapp"

export default ({ data }) => (_, actions) => {
  // lazy(function, [array of properties])
  // the properties get passed to the function when needed
  return lazy(Row, [data, actions.select, actions.delete])
}

function Row(data, select, del) {
  const { id, label, selected } = data
  return (
    <tr key={id} class={selected ? "danger" : ""}>
      <td class="col-md-1">{id}</td>
      <td class="col-md-4">
        <a onclick={_ => select(id)}>{label}</a>
      </td>
      <td class="col-md-1">
        <a onclick={_ => del(id)}>
          <span class="glyphicon glyphicon-remove" aria-hidden="true" />
        </a>
      </td>
      <td class="col-md-6" />
    </tr>
  )
}
```

Will do my best to get a PR ready in the next couple of days as I get time. :smile:

**Comment by jorgebucaran** [comment]
> @SkaterDad I'm look forward to combining these lazy functions with the custom JSX optimizations to get the best of both worlds: faster node creation, and faster partial updates.

Just to clarify, the results you shared [here](https://github.com/hyperapp/hyperapp/issues/564#issuecomment-375455642) don't combine both optimizations, but instead show only the lazy optimizations, correct?

**Comment by SkaterDad** [comment]
> @jorgebucaran Just to clarify, the results you shared here don't combine both optimizations, but instead show only the lazy optimizations, correct?

Yes, that's correct.

**Comment by frenzzy** [comment]
What if use [Prepack](https://prepack.io/) as a final optimization of the bundle instead of trying to optimize only vnodes creation? Will it improve performance significantly?

**Comment by jorgebucaran** [comment]
Thank you, @SkaterDad, for pioneering this feature. Introducing laziness is the next step after 2.0. 🎉 

---

I've never actually tried @frenzzy. 🤔

**Comment by SkaterDad** [comment]
@jorgebucaran My pleasure!
