### ISSUE TITLE
Some small ideas for the documentation

### ISSUE THREAD

**Issue by Mytrill** [hyperapp/hyperapp#572]
Hi there,

I had a look at the docs, and I have a few remarks/suggestions/ideas.
These are all based on opinion, so feel free to reject the ones you disagree with:
 - at the end of hello world, add a "next" link to the advanced concepts and a link to the examples for easier navigation
 - at the top (or the end?!) of the advanced concepts, add a link to the hello world and to the examples for easier navigation
 - rename hello-world to overview or main concepts or introduction: I believe this doc is more about introduction to the concepts rather than building a hello world (it's actually a counter!)
 - in the documentation's root README.md, add direct link to all the examples, to avoid having to click through 2 pages to see a specific example:

* [Hello World](hello-world.md)
* [Advanced Concepts](advanced.md)
* [Tutorials](tutorials)
  * [TweetBox](tutorials/tweetbox.md)
  * [Gif Search](tutorials/gif-search.md)
  * [Countdown Timer](tutorials/countdown-timer.md)

**Comment by JorgeBucaran** [comment]
Looks good!

**Comment by algebraic-brain** [comment]
@JorgeBucaran Great documentation now, thanks a lot! But why tutorials disappeared? I still use them, and fortunately codepen-links are saved in my browser history. But what if I loose them?

**Comment by Mytrill** [comment]
With #579 this issue is no longer relevant.
I'll close this now
PS: if that's OK with everyone and the tutorial are not coming back here, I'll add the tutorials' code to hyperapp-recipes?

**Comment by JorgeBucaran** [comment]
@Mytrill I think recipes share a resemblance with tutorials, but they are ultimately a how-to guide of general topics. The tutorials we used to have were not even a "tutorial" in the traditional sense of a step-by-step guide, but just an explanation of how a particular code example worked.

I think the ideal thing to do here would be to take ideas from the old tutorials and turn them into a real recipe. For example, instead of explaining how to build a TweetBox, explain how to break up your UI using components, etc.

**Comment by Mytrill** [comment]
Ok,
I will have more time to work on this repo over the weekend, I'll try to add this stuff then :)
Thanks!

**Comment by algebraic-brain** [comment]
@JorgeBucaran Just put codepen links directly in the documentation, it's enough I think.
