### ISSUE TITLE
Hyperapp Community Projects

### ISSUE THREAD

**Issue by JorgeBucaran** [hyperapp/hyperapp#610]
For current and new <samp>npm</samp> modules: Do we want to publish them as [**@hyperapp**/gizmo scoped packages](https://docs.npmjs.com/misc/scope) or regular <samp>hyperapp-gizmo</samp> prefixed packages?

**Comment by Siilwyn** [comment]
Babel is also looking to use scoped packages, might be worth looking how & if they pick it up: https://babeljs.io/blog/2017/09/12/planning-for-7.0#using-npm-scoped-packages

**Comment by JorgeBucaran** [comment]
Whatever path we choose, I hope most of those repos & projects can live under the new [**HyperappCommunity**](https://github.com/HyperappCommunity) organization

**Comment by frenzzy** [comment]
I think we should not publish community projects under `@hyperapp` scope while we do not have naming collisions between repo owners. And it also less work for both `@hyperapp` npm scope owner and repo owner. I would reserve `@scope` for possible future official packages.

**Comment by whaaaley** [comment]
Scopes!!!

I like being able to do a quick poke into `node_modules` to see what kind of stuff is being used.

**Comment by SkaterDad** [comment]
I like the idea of using the `@hyperapp/` scope for HyperappCommunity packages, but who manages the publishing rights?

**Comment by JorgeBucaran** [comment]
@SkaterDad Yes, that's the other issue. It's more work. I wouldn't mind inviting more people to the npm org (we have like 4 or 5 people currently there already).

**Comment by okwolf** [comment]
Looks like we're using the @scoped packages now: https://www.npmjs.com/package/@hyperapp/transitions

**Comment by JorgeBucaran** [comment]
Let's make it worth it! Only the creme de la creme. 🍨

**Comment by zaceno** [comment]
@okwolf @JorgeBucaran Didn't mean to claim that `transitions` is creme-de-la-creme 😉   Sorry if I jumped the gun on this! -- I plead confusion from the many moves and directives that came in a short period of time.  The reasons I did it: 

- It bugged me to have `hyperapp` in the repo name since it's already under (the very long) `HyperappCommunity`. So I changed the name. And I like my packages named same as the repo.

- Some packages in the community org are already doing it that way (html, router et al). Moving them to the community in a way sets a standard for how repos should be named and published.  (Unless we plan to name them `hyperapp-router` et c)

- From here and slack I got the impression that the majority consensus, although not unanimous, is in favor of @-scoped packages.  

... so it seemed the natural next step. But don't worry -- I can go back to publishing under the name `hyperapp-transitions` no problem :) 

(And I'll hold off renaming my other packages awaiting further comments)

**Comment by zaceno** [comment]
@JorgeBucaran I think there should be a standard among community packages -- or the community will look very messy. Perhaps the "creme-de-la-creme"-criterion should be a bar for being moved into community? (I say that realizing that some/all of my packages might be moved back out if that's how we decide)

**Comment by JorgeBucaran** [comment]
@zaceno The three defining moments in the life of a Hyperapp Gizmo.

1. username/hyperapp-gizmo
2. HyperappCommunity/hyperapp-gizmo
3. hyperapp/gizmo

**Comment by zaceno** [comment]
@JorgeBucaran 👍  good structure!

 As you know, at first I advocated only a single org, but I see now that comes with ownership/curation issues. This structure is good.

**Comment by JorgeBucaran** [comment]
@zaceno To be honest, right now I would prefer to go back to:

(1) and then (3) if the module gets to that level. But I had to write that up because, after all, I am the one who is responsible for the whole mess. 😓

**Comment by zaceno** [comment]
Makes sense too. I wouldn't mind moving my packages back to zaceno/gizmo. There's always the awesome-list to get exposure. Except ... as long as there *is* a HyperappCommunity, I think that's where I want my packages, just not to give the impression that they're somehow experimental (unless they are ;) )

But if you decide to shut it down and have everyone move their packages back, that's fine with me!

**Comment by JorgeBucaran** [comment]
@zaceno Well done. I went ahead and deleted it. Now it's only <samp>github.com/hyperapp</samp>.

**Comment by JorgeBucaran** [comment]
### Conclusion

Got a cool idea for a module you want to make that depends on hyperapp or extends hyperapp functionality, e.g., a higher order app, a utility library, a helper function? Use this simple [template](https://gist.github.com/JorgeBucaran/533f75c2330cf79afc2e622ad7a07e84) and publish it on npm as hyperapp-foo.

Think your module is relevant enough to be published as an "official", <samp>@hyperapp/foo</samp>? Create an issue or let us know on Slack and we'll take it for consideration. If it's approved, you'll be invited to the Hyperapp GitHub and npm organization so you can take care of your own module.
