### ISSUE TITLE
Is it possible to share states between multiple roots?

### ISSUE THREAD

**Issue by van-nguyen** [hyperapp/hyperapp#661]
https://codepen.io/van-nguyen/pen/WzEGbV

They reference the same originating objects, but seems the default behaviour is that it creates it's own instances? If it's not possible, is there a way for the two apps to "talk" with each other? Maybe via events?

**Comment by lukejacksonn** [comment]
You can link the two apps by whatever global event bus you like, be that a web socket, the browsers synthetic events or any other pub sub style implementation.

I was once playing around with this and distilled it down to:

```
const pub = e => detail => dispatchEvent(new CustomEvent(e, { detail }))
const sub= e => f => addEventListener(e, ({detail}) => f(detail))
```

You can see this working in [a fork of your pen](https://codepen.io/lukejacksonn/pen/wmqzYa)

I never actually used it, if you do lmk how it goes! Usually if i am going to distribute my state amongst apps, I will do it with a remote store like firebase and then have each app subscribe to it. Then they will always be synced, wether in different DOM containers, browser windows or different devices.

**Comment by jorgebucaran** [comment]
@van-nguyen Your pen behaves as expected and no, there is no prescribed way for two apps to communicate with each other. It should be possible because the `app()` call returns the wired actions of that particular application, allowing you to dispatch actions to your app from another app that may not even be written in Hyperapp. 

Good luck!

---

**Offtopic**: You don't need to put `const React = {createElement: h}` in your file, instead add a pragma comment like this: `// @jsx h`.
