### ISSUE TITLE
There is a pattern that `oncreate` does not work.

### ISSUE THREAD

**Issue by nishiurahiroki** [hyperapp/hyperapp#731]
Hi, excuse me for my poor English.

There is a pattern that `oncreate` of lifecycle does not work.

It is the case as follows.
```js
// rootState.js
export default {
 currentView : () => {/** place to display current view jsx. **/}
}
```

```jsx
// rootView.js
export default ({currentView}, action) => (
 <div>
  {currentView}
 </div>
)
```

```js
// rootAction.js
export default = {
 changeView : currentView => () => ({currentView})
}
```

On the following logic, oncreate does not work.
```jsx
// rootAction.js
const PreviewViewDiv = (
  <div oncreate={() => console.log('show preview view')}>
    view 1
  </div>
)

const NowLoadingDiv = (
  <div oncreate={() => console.log('show now loading')}>
    now loading...
  </div>
)

const NextViewDiv = (
  <div oncreate={() => console.log('show next view')}>
    view 2
  </div>
)

export default = {
 changeView : currentView => () => ({currentView}),
 doHoge : () => (state, action) => {
   action.changeView(<NowLoadingDiv/>)  // console -> `show now loading`. work oncreate.
   action.changeView(<PreviewViewDiv/>)   // console -> nothing displayed.  don't work oncreate.
   action.changeView(<NowLoadingDiv/>)  // console -> nothing displayed.  don't work oncreate.
   action.changeView(<NextViewDiv/>)       // console -> nothing displayed.  don't work oncreate.
 }
}
```

Following the processing of [hyperapp's index.js](https://github.com/hyperapp/hyperapp/blob/master/src/index.js#L290) , inside of the `patch` function, the` oldNode` By referring to `nodeName`, I felt as if it was due to the behavior of` createElement` or `updateElement` branching the processing.

https://github.com/hyperapp/hyperapp/blob/ebe173af6e11812e4abce9ad95b15a9092c3ef86/src/index.js#L290-L293

In step, it is thought that the value comes in `nodeName` as follows each time.
```js
    } else if (oldNode == null || oldNode.nodeName !== node.nodeName) { // For example,nodeName -> `div`, `span`, `button`, `input` etc...
```

So, even with the same logic, `oncreate` will work in the following configuration.
```jsx
// rootAction.js
const PreviewViewSpan = (
  <span oncreate={() => console.log('show preview view')}>
    view 1
  </span>
)

const NowLoadingDiv = (
  <div oncreate={() => console.log('show now loading')}>
    now loading...
  </div>
)

const NextViewSpan = (
  <span oncreate={() => console.log('show next view')}>
    view 2
  </span>
)

export default = {
 changeView : currentView => () => ({currentView}),
 doHoge : () => (state, action) => {
   action.changeView(<NowLoadingDiv/>)     // console -> `show now loading`. work oncreate.
   action.changeView(<PreviewViewSpan/>)  // console -> `show preview view`. work oncreate.
   action.changeView(<NowLoadingDiv/>)    // console -> `show now loading`. work oncreate.
   action.changeView(<NextViewSpan/>)      // console -> `show next view`. work oncreate.
 }
}
```
Perhaps because `nodeName` is determined as` div -> span -> div -> span`, it seems to be because `createElement` fires each time and` oncreate` also fires accordingly.

that's all.

It is not possible to judge whether it is bug or hyperapp's anti-pattern usage, how is it?

**Comment by zaceno** [comment]
oncreate is only being called once because the div in your views is created just once, the first time. Next view, it’s already created so hyperapp will not destroy and create it again

To force hyperapp to destroy and create it when you switch views, give each view a different key. Then oncreate will be called when you switch views.

**Comment by nishiurahiroki** [comment]
@zaceno 
Thank you for answer.
I understood it.
For performance it's like being made like this.

Including the point that it can generate again by giving the key, it became very helpful.

**Comment by jorgebucaran** [comment]
Thanks for your question @nishiurahiroki. Please read the section on [_keys_](https://github.com/hyperapp/hyperapp#keys) if you still haven't (also [this article](https://reactjs.org/docs/reconciliation.html) in React's docs is relevant). 

Keys or "keyed-based DOM reconciliation" is one of the major concepts one needs to understand well to use VDOM to the fullest.

**Comment by nishiurahiroki** [comment]
@jorgebucaran 
The concept of key was meant to understand when using react, but it was not understood at all.

I love react and jsx, and the idea of hyperapp, so I would like to read more about React's forum and ReadMe that you taught and deepen your understanding of VDOM.

Thank you for answering my poor question!

I love hyperapp!

**Comment by jorgebucaran** [comment]
Thanks, @nishiurahiroki!

Every time the view function is called we create a new tree of vnodes. Vnodes have a one-to-one relation with DOM elements, but new vnodes don't know what elements they are paired with until we've patched them.

We need keys when we want Hyperapp to preserve elements (swap/move instead of creating from scratch). By declaring keys, Hyperapp knows what elements belongs to which keyed vnodes because we already have the previous vnode tree.

Hope that helps a bit!

**Comment by nishiurahiroki** [comment]
In the present explanation, it seems that lyfecycle images such as oncreate, onupdate, ondestroy, etc. will be clearer.
Until now I may not have been able to master these lyfecycle in the real sense.

The idea of "reconciliation" was intended to be understood when react version 16 was released, but in fact I felt that understanding was not enough.

@jorgebucaran 
Thank you very much! I am learning really.

**Comment by jorgebucaran** [comment]
@nishiurahiroki I'm glad you are in the process of mastering them. I've been (and still am) refining my own understanding of these concepts (keyed-based reconciliation being just one of them) since the beginning. I really owe it to @zaceno, @SkaterDad, @mindplay-dk, @leeoniya, @localvoid and @yelouafi who all have helped in one way or another with their code, comments, feedback and advice! 🎉 

---
