### ISSUE TITLE
Images CDN URL lost on state hydration (on Netlify)

### ISSUE THREAD

**Issue by gyopiazza** [hyperapp/hyperapp#741]
Hello all,

I'm creating a little static website hosted on Netlify and I've chosen Hyperapp for its addictively elegant syntax and overall code simplicity. So far so good, I'm in love with the framework and I've also added a simple state hydration which works fine... except for a **flickering on page load**.

After debugging the issue – unless I'm doing something terribly wrong – it's 99% related to a feature at **Netlify** that **replaces all the images URLs in the rendered HTML files with their CDN**. Since the state is hydrated from the original URLs which are absolute paths (not the ones from Netlify which cannot be "prefetched"), the mismatch causes a repaint flickering which also causes a double loading of the images (the ones from the CDN and the "originals" from the hydrated state).

I guess this issue is not exclusively related to Hyperapp – it's more of a general thing – but I'd like to know if you have any ideas on how this could be solved with Hyperapp without disabling the CDN, if possible.

As a solution I was thinking to ignore certain tags/attributes from the diff, based on some filtering (a function maybe). The idea is to tell HA not to update a certain tag depending on a custom function that might check the tag "src" or any other attributes. It could also determine the updates by checking a state condition or serve to throttle a specific update/repaint. However I'm not sure if this can be done already.

My current implementation renders the static site pages using:
`withRender(app)(state, actions, view).toString()`

In the view, the hydrated state is set in a template tag (please note I'm not using the whole state in the actual code):
`<template id="hydration" innerHTML={new Buffer.from(JSON.stringify(state)).toString('base64')}></template>`

In the frontend, the original state is re-hydrated (patched) with the #hydration template (a base64 encoded JSON):
`window.app = app(state, actions, view, document.body)`

Thank you!

**Comment by frenzzy** [comment]
Hydration (recycling) of `innerHTML` is not supported, see https://github.com/hyperapp/hyperapp/pull/688

But you can use lifecycle events like this:
`<template oncreate={(el) => { el.innerHTML = 'blabla' }} />`

**Comment by gyopiazza** [comment]
@frenzzy I've been fiddling with the `oncreate` event as you suggested but it seems to be fired only frontend and not via `withRender()`.

About the CDN URLs, I've "fixed" them on the frontend by querying the DOM for all the images and patching the state accordingly (yeah, it's a dirty hack but it prevents the double images loading for now).

I see your point about the `innerHTML` not being re-hydrated correctly because the whole app's `<div>` repaints and – even though there is no flickering because the state is exactly the same – it delays the "time to interactive" (the images hack contributes to the issue).

Or maybe the repaint is a predicted behaviour during re-hydration even when the state match?

Thanks for the feedback!

**Comment by jorgebucaran** [comment]
Hi, @gyopiazza! Thank you for your issue and glad to hear you are using Hyperapp and liking it!

If you are having trouble with Hyperapp's built-in hydration capabilities as described in the [Mounting](https://github.com/hyperapp/hyperapp#mounting) section of the documentation, please create a new issue explaining the problem concisely and, if possible, include a short, self-contained, correct and reproducible demo (http://sscce.org).

If you believe the problem is not Hyperapp-specific, then please [join our Slack](https://hyperappjs.herokuapp.com/) and feel free to discuss it in the <samp>#general</samp> section.

If you are having trouble with [hyperapp/render](https://github.com/hyperapp/render), please create an issue in that repository. Be aware that Hyperapp and HyperappRender only co-exist in the same organization. I don't officially support that package.

Cheers! 👋

**Comment by frenzzy** [comment]
@jorgebucaran there are a bug in hyperapp: it removes correctly generated markup during recycling (hydration) if you use `innerHTML` attributes (workaround for this issue is [here](https://github.com/hyperapp/render/issues/8#issuecomment-385974406)).

Maybe you can re-consider merging PR #688 to fix the issue?
There are two test from the PR which are failed in the master branch.

**Comment by jorgebucaran** [comment]
I replied here https://github.com/hyperapp/hyperapp/pull/688#issuecomment-386862823.
