### ISSUE TITLE
What are the design goals of this project? 🎯 

### ISSUE THREAD

**Issue by nichoth** [hyperapp/hyperapp#9]
Hi. Cool repo. I was wondering if you have goals for the project and how they might differ from existing libraries (there are so many). For example, `choo` comes to mind as having a similar elm-like design.

**Comment by sotayamashita** [comment]
@nichoth I would like to know, too but `choo` is quite a different.

**Comment by jbucaran** [comment]
@nichoth & @sotayamashita 

Let's see, first here's some history.

### Why?
I was building a web client for a project at work. My first choice was React+Redux, since that's what we already use, but I wanted something more lightweight and without the frameworkyness of React. So no complex frameworks like Angular, Ember or Aurelia either.

### Elm
I made the first prototype using Elm, which I really like, but it was [too difficult](https://github.com/elm-lang/elm-lang.org/tree/master/src/editor) to integrate with 3rd party components, e.g. CodeMirror.

### yo-yo/choo
Next I tried [yo-yo](https://github.com/maxogden/yo-yo). yo-yo is an abstraction on top of [bel](https://github.com/shama/bel) and [morphodom](https://github.com/patrick-steele-idem/morphdom) (which mutates DOM nodes directly) whereas I preferred a virtual DOM approach like Snabbdom. 

There's choo too, an abstraction on top of yo-yo with a much nicer API.

1. Since they're dealing with real HTML elements, they had to come up with a way to have lifecycle events for DOM nodes using the [MutationObserver API](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) which seems like code smell to me.

2. They [don't support CSS](https://github.com/shama/bel/issues/10#issuecomment-273301122) out of the box either, so I had to use [dom-css](https://www.npmjs.com/package/dom-css).

3. I also couldn't agree with some of choo API choices like namespaces and their router design, but I still think choo is cool.

### The deal breaker

Too hard to integrate with 3rd party components, involving the creation of a [portal](https://github.com/trainyard/choo-codemirror#choo-codemirror), reminiscent of Elm [ports](https://guide.elm-lang.org/interop/javascript.html). 

![](https://cloud.githubusercontent.com/assets/56996/22538810/9665b902-e958-11e6-8b5e-fc1762bd1237.png)

### HyperApp
~1kb. It's almost vanilla. No deps, other than [Hyperx](https://github.com/substack/hyperx) (itself no deps) which is how we write HTML using JavaScript, but [without breaking JavaScript](https://github.com/substack/hyperx/issues/2). You can still use [JSX if you want](https://jasonformat.com/wtf-is-jsx/).

HyperApp includes Elm-like state management, a router and a tiny virtual dom implementation with support for [SVG](https://hyperapp.gomix.me/svg_clock), inline CSS, boolean HTML attributes and _on_ create, update and remove hooks.

**Comment by nichoth** [comment]
Thanks for the awesome explanation @jbucaran. Did you end up using this library for your work project? How has that been? Do you have plans for the future direction of this repo?

I agree with your points, that's basically where I'm at too. yoyo and choo I think are very cool experiments, but some of the design decisions have created some extra complexity. The namespace/state pattern, and direct dom mutation have made some things difficult (not to say that I've made something nicer). Though also choo has grown a lot, which may have added more to the scope.

Can you elaborate on the use of MutationObserver and code smell?

**Comment by acstll** [comment]
hey @jbucaran I know you from `snabbdom` :)

I'm amazed by the simplicity of the code, I really like it.

Some comments/questions in my head right now:

(1) are you planning to add tests to the library? I wouldn't feel comfortable using it in production without…

(2) since this is somewhat similar to `choo` (I could recognize it before reading here) it'd be lovely if you included the above explanation in the README

(3) the only thing I would miss are "hooks" for elements (like in `snabbdom`), (correct me if I'm wrong)

**Comment by nichoth** [comment]
Yeah I was thinking the same things @acstll . Very nice experiment in finding the most minimal implementation of the elm pattern, and the code is so simple. Was also wondering about what tests would look like.

**Comment by jbucaran** [comment]
@nichoth 

> Did you end up using this library for your work project?

Yes. I upgraded our project to use HyperApp from yo-yo (and my own [yo-yo-app](https://gist.github.com/jbucaran/4dfa567e38ca222c25c46184b3a5df99) a few weeks ago).

<details>
<summary>Screenshot</summary>

![hyperapp](https://cloud.githubusercontent.com/assets/56996/22575917/08e192c8-e9fc-11e6-9479-ac8eb74f1489.png)
</details>
<br />

> Can you elaborate on the use of MutationObserver and code smell?

Well, it seems lifecycle events don't make sense if you are working directly with the DOM, e.g. using morphodom. The DOM has no onload/onunload for individual elements. So, in order to support on load/unload events for DOM elements they use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) which adds much [complexity](https://github.com/shama/on-load).

@acstll 
> (1) are you planning to add tests to the library? I wouldn't feel comfortable using it in production without…

I know, and _yes_, soon! 🙇 

> (2) since this is somewhat similar to choo (I could recognize it before reading here) it'd be lovely if you included the above explanation in the README

Totally. Maybe we can add a FAQ in the future!

> (3) the only thing I would miss are "hooks" for elements (like in snabbdom), (correct me if I'm wrong)

It's just missing in the docs. The term I'm planning to use is _lifecycle events_, since we're already using [hooks](https://github.com/hyperapp/hyperapp#hooks) for something else.

Supported events are:

* oncreate
* onupdate
* onremove

<details>
<summary>Expand</summary>

```js

app({
    model: 0,
    update: {
        toggle: model => model === 0 ? 1 : model === 1 ? 2 : 0
    },
    view: (model, msg) => html`
        <div>
            ${model > 0
            ? html`
                <ul>
                    <li style=${{ color: model === 1 ? "inherit" : "deepskyblue" }}>
                        Leonardo
                    </li>

                    <li style=${{ color: model === 1 ? "inherit" : "orange" }}>
                        Michelangelo
                    </li>

                    <li style=${{ color: model === 1 ? "inherit" : "red" }}>
                        Raphael
                    </li>

                    <li style=${{ color: model === 1 ? "inherit" : "purple" }}
                        onupdate=${_ => console.log("UPDATE")}
                        oncreate=${_ => console.log("CREATE")}
                        onremove=${_ => console.log("REMOVE")}>Donatello
                    </li>
                </ul>`
            : html`
                <ul>
                    <li>Krang</li>
                </ul>`
        }
            <button onclick=${msg.toggle}>Mutate!</button>
        </div>`,
})
```

> Sorry about this somewhat obfuscated example. I put it together hastily.

[**CodePen**](http://codepen.io/jbucaran/pen/apGNYx?editors=0010)


</details>

**Comment by terkelg** [comment]
+ The virtual DOM approach is faster in most benchmarks vs compared to morphodom.

**Comment by jbucaran** [comment]
@terkelg It seems so. 

* https://github.com/hyperapp/hyperapp/issues/13

**Comment by jbucaran** [comment]
A lot has changed since you opened this issue @nichoth 👋. 

The core values of the project still remain to be a small (or the smallest) JavaScript frontend framework that is useful out of the box and implements a sane subset of the Elm Architecture, supports Hyperx, JSX and it's easy to learn.
