### ISSUE TITLE
Should we care about requestAnimationFrame?

### ISSUE THREAD

**Issue by jbucaran** [hyperapp/hyperapp#90]
The [initial commit](https://github.com/hyperapp/hyperapp/blob/b5cc01f06b5e62d1ad1a78b7d9b073369ce5dd05/index.js#L24) of hyperapp demonstrates how to use [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame to batch view renderings, largely based in [Raynos/main-loop](https://github.com/Raynos/main-loop).

At the time, I was using Matt-Esch/virtual-dom, but when I moved to Snabbdom I dropped this in favor of whatever Snabbdom was doing. Now that we're using a in-house vdom algorithm, it is worth considering using requestAnimationFrame again.

Ideally this would come after https://github.com/hyperapp/hyperapp/issues/75.

**Comment by dodekeract** [comment]
I think it's a good idea. Depending on the effects used the state might be updated more than 60 times per second, which would probably lead to high CPU usage, etc.

E.g. I planned to use hyperapp when re-writing @smartflat. It'd easily be possible to get more than 60 sensor updates per second in that particular project.

**Comment by terkelg** [comment]
Always nice with performance optimisations and I think no matter what we should provide examples on how to do this in the documentation.

Personally I'd prefer not to have it included, because I often work on projects that involve a lot of canvas, WebGL, tweening etc. and to avoid multiple `requestAnimationFrame` all over the place I just have a single main loop, which all other code subscribe to.

That being said, I guess it's in most peoples interest to have stuff like this included out of the box and it's what most virtual dom implementations do. It could be fun to do some performance testing, and see how much it actually does for the performance.

*@dodekeract @smartflat looks really interesting! Nice one.*

**Comment by jbucaran** [comment]
> It could be fun to do some performance testing, and see how much it actually does for the performance.

This. I haven't had time to work on new benchmarks since http://mathieuancelin.github.io/js-repaint-perfs/hyperapp/, but I also want to see how much it would mean for performance.

**Comment by jbucaran** [comment]
Example: 
* http://codepen.io/anon/pen/GWKONK?editors=0010

/cc @tzellman

**Comment by jbucaran** [comment]
Close in favor of #286.
